import type { BncAlertCase, BncCaseListData } from '@/types/bnc';

export const MOCK_BNC_ALERT_CASES: BncAlertCase[] = [
  {
    caseId: 'case-de-fe-72-20260607-0115',
    tgId: 'tg-de-fe-72',
    tgName: 'DE_FE_72',
    areaName: 'Dry Etch',
    riskGrade: 'CRITICAL',
    bottleneckProb: 0.999,
    utilizationRate: 0.897,
    wipCount: 261,
    detectedAt: '2026-06-07T01:15:00Z',
    status: 'ANALYZING',
    currentStepName: 'CAUSE_ANALYSIS',
    stepProgress: 2,
    totalSteps: 6,
  },
  {
    caseId: 'case-litho-be-110-20260607-0035',
    tgId: 'tg-litho-be-110',
    tgName: 'Litho_BE_110',
    areaName: 'Lithography',
    riskGrade: 'CRITICAL',
    bottleneckProb: 0.974,
    utilizationRate: 0.912,
    wipCount: 312,
    detectedAt: '2026-06-07T00:35:00Z',
    status: 'RESOLVED',
    currentStepName: 'REPORT_GENERATION',
    stepProgress: 6,
    totalSteps: 6,
  },
  {
    caseId: 'case-de-be-67-20260606-2350',
    tgId: 'tg-de-be-67',
    tgName: 'DE_BE_67',
    areaName: 'Dry Etch',
    riskGrade: 'CRITICAL',
    bottleneckProb: 0.951,
    utilizationRate: 0.884,
    wipCount: 244,
    detectedAt: '2026-06-06T23:50:00Z',
    status: 'AWAITING_HITL',
    currentStepName: 'HITL_REVIEW',
    stepProgress: 5,
    totalSteps: 6,
  },
  {
    caseId: 'case-litho-reg-be-63-20260606-2310',
    tgId: 'tg-litho-reg-be-63',
    tgName: 'Litho_REG_BE_63',
    areaName: 'Lithography',
    riskGrade: 'HIGH',
    bottleneckProb: 0.823,
    utilizationRate: 0.861,
    wipCount: 198,
    detectedAt: '2026-06-06T23:10:00Z',
    status: 'ANALYZING',
    currentStepName: 'ACTION_PLAN_GENERATION',
    stepProgress: 4,
    totalSteps: 6,
  },
];

export const MOCK_BNC_CASE_LIST: BncCaseListData = {
  items: MOCK_BNC_ALERT_CASES,
  pageInfo: {
    page: 0,
    size: 20,
    totalElements: MOCK_BNC_ALERT_CASES.length,
    totalPages: 1,
    sort: 'detectedAt,desc',
  },
};
