import { MOCK_FINAL_BOTTLENECK_REPORT } from '@/constants/mockData/finalBottleneckReport';

import type { BncActionPlansPayload, BncCauseAnalysis, BncReportPayload } from '@/types/bnc';
import type { ReportV1 } from '@/types/report';

// 이번 세션에서 만든 단일 데모 케이스: stage1_alert_t2520 + stage2_cause_t2520 의 Critical 병목.
const DIFFUSION_FE_125_CASE_ID = 'case-diffusion-fe-125-t2520';

// stage2_cause_t2520.json(Diffusion_FE_125)을 그대로 옮긴 원인분석.
const DIFFUSION_FE_125_CAUSE: BncCauseAnalysis = {
  caseId: DIFFUSION_FE_125_CASE_ID,
  analysisId: `analysis-${DIFFUSION_FE_125_CASE_ID}`,
  predictionSummary: {
    bottleneckProb: 0.9941,
    riskGrade: 'CRITICAL',
    maxWipCount: 5,
    maxUtilizationRate: 0.7914,
  },
  diffusion: { affectedToolGroups: [] },
  causeSummary: [],
  shapFeatures: [
    {
      feature: 'max_util_delta_120',
      label: '최대 가동률 120분 변화',
      importance: 0.387,
      rank: 1,
      direction: '병목 쪽으로 기여(+)',
      shapValue: 1.8853,
      kpiValue: 0.0,
      contributionPct: 38.7,
    },
    {
      feature: 'max_util',
      label: '최대 가동률',
      importance: 0.333,
      rank: 2,
      direction: '병목 쪽으로 기여(+)',
      shapValue: 1.6214,
      kpiValue: 1.0,
      contributionPct: 33.3,
    },
    {
      feature: 'wip',
      label: 'WIP',
      importance: 0.195,
      rank: 3,
      direction: '병목 쪽으로 기여(+)',
      shapValue: 0.9499,
      kpiValue: 5.0,
      contributionPct: 19.5,
    },
    {
      feature: 'utilization_avg',
      label: '평균 가동률',
      importance: 0.086,
      rank: 4,
      direction: '병목 쪽으로 기여(+)',
      shapValue: 0.4173,
      kpiValue: 0.7914,
      contributionPct: 8.6,
    },
  ],
  trendInsights: [
    { feature: 'q_time_min', label: '평균 대기시간', slopePerHour: 1.3957, values: [], r2: 0.429, significant: false },
    { feature: 'wip', label: 'WIP', slopePerHour: 0.5143, values: [], r2: 0.631, significant: true },
    {
      feature: 'utilization_avg',
      label: '평균 가동률',
      slopePerHour: 0.0743,
      values: [],
      r2: 0.834,
      significant: true,
    },
  ],
  ragSimilarCases: [
    {
      caseId: 'DefMet_FE_43',
      score: 0.94,
      tgCode: 'FE-DIFF-125',
      reportTitle: '2026-06 확산로 포화 대응',
      summary: '동일 TG 가동률 포화로 WIP 급증. REQUEUE_TOOL 적용 후 30분 내 wait_ratio 57% 감소.',
    },
    {
      caseId: 'Litho_BE_110',
      score: 0.87,
      tgCode: 'BE-LITHO-110',
      reportTitle: '2026-05 리소 WIP 급등',
      summary: '리소 공정 WIP 누적, LOT_HOLD 보류 조치로 Q-time 40분 단축 및 안정화.',
    },
    {
      caseId: 'CMP_BE_12',
      score: 0.72,
      tgCode: 'BE-CMP-12',
      reportTitle: '2026-05 CMP 가용률 저하',
      summary: 'CMP 설비 가용률 하락, 병목 범위 협소해 표준 재배정으로 대응. 60분 내 정상화.',
    },
    {
      caseId: 'Photo_FE_28',
      score: 0.65,
      tgCode: 'FE-PHOTO-28',
      reportTitle: '2026-05 포토 공정 지연',
      summary: '포토 대기 증가 패턴 유사. 공급 부족 원인은 기각됨. 소폭 개선 후 재발.',
    },
  ],
  modelPerformance: {
    accuracy: 0.923,
    f1Score: 0.891,
    featureCount: 19,
  },
  judgment: {
    primaryCategory: '설비_포화',
    primaryCause: 'max_util',
    primaryConfidence: 'HIGH',
    primaryReasoning:
      '설비_포화가 total score 0.955로 가장 높고 SHAP 기여율도 80.5%로 압도적입니다. 대표 피처 max_util의 SHAP 기여가 +1.621로 병목 방향이며, max_util_delta_120(+1.885)와 utilization_avg(+0.417, Trend★+0.074/h)도 함께 상승해 설비 포화가 주된 원인으로 판단됩니다.',
    secondaryCauses: ['WIP_누적'],
    dismissed: ['대기_누적', '공급_부족'],
    dismissedReason:
      '대기_누적과 공급_부족은 각각 score 0.080, SHAP 기여 0.0%로 근거가 약해 주원인으로 보기 어렵습니다.',
    causeSummary:
      '[주요 원인] 설비_포화(max_util 중심)로 인한 병목이 핵심입니다. [악화 추세] max_util_delta_120과 utilization_avg가 함께 상승하며 설비 사용률이 더 악화되는 흐름입니다. [업스트림] WIP_누적은 보조적으로 존재하며 wip가 +0.950, Trend★+0.514/h로 누적 추세가 관찰됩니다.',
  },
  causeCategories: [
    {
      name: '설비_포화',
      features: ['max_util', 'max_util_delta_120', 'utilization_avg'],
      shapSharePct: 80.5,
      nTrendSignificant: 1,
      upstreamMatch: false,
      gStarConfirmed: false,
      totalScore: 0.9551,
      confidence: 'HIGH',
    },
    {
      name: 'WIP_누적',
      features: ['wip'],
      shapSharePct: 19.5,
      nTrendSignificant: 1,
      upstreamMatch: true,
      gStarConfirmed: false,
      totalScore: 0.4249,
      confidence: 'MEDIUM',
    },
    {
      name: '대기_누적',
      features: ['wait_ratio', 'q_time_min'],
      shapSharePct: 0,
      nTrendSignificant: 0,
      upstreamMatch: true,
      gStarConfirmed: false,
      totalScore: 0.08,
      confidence: 'LOW',
    },
    {
      name: '공급_부족',
      features: ['available_tool_ratio'],
      shapSharePct: 0,
      nTrendSignificant: 0,
      upstreamMatch: true,
      gStarConfirmed: false,
      totalScore: 0.08,
      confidence: 'LOW',
    },
  ],
  upstreamSuspects: ['WE_FE_84', 'DE_FE_86'],
  gStar: {
    confirmed: true,
    proba: 0.9967,
    nTotal: 0,
    nAlarm: 0,
    toolgroups: ['Diffusion_FE_44', 'DE_FE_51', 'DE_FE_86'],
    sigKpis: [
      { kpi: 'utilization_avg', deltaMean: 0.399, pAdjusted: 0.0, significant: true },
      { kpi: 'q_time_min', deltaMean: -1.397, pAdjusted: 1.0, significant: false },
      { kpi: 'wait_ratio', deltaMean: -0.231, pAdjusted: 1.0, significant: false },
      { kpi: 'available_tool_ratio', deltaMean: 0.0, pAdjusted: 1.0, significant: false },
    ],
    upstreamConfirmed: [],
  },
  simForecast: {
    t0: 3180,
    tFuture: 4380,
    getsWorse: false,
    kpiDeltas: [
      { kpi: 'wip', now: 7.0, future: 0.0, delta: -7.0, pctChange: -100.0, reliability: 'HIGH' },
      { kpi: 'wait_ratio', now: 0.22, future: 0.0, delta: -0.22, pctChange: -100.0, reliability: 'HIGH' },
      { kpi: 'available_tool_ratio', now: 1.0, future: 1.0, delta: 0.0, pctChange: 0.0, reliability: 'HIGH' },
      { kpi: 'utilization_avg', now: 0.15, future: 0.12, delta: -0.03, pctChange: -21.6, reliability: 'MEDIUM' },
    ],
  },
  forwardForecastText:
    '[주요 원인] 설비_포화(max_util 중심)로 인한 병목이 핵심입니다. [악화 추세] max_util_delta_120과 utilization_avg가 함께 상승하며 설비 사용률이 더 악화되는 흐름입니다.',
  createdAt: '2026-06-14T10:02:00Z',
};

// 제공된 JSON 기반 대응안 비교 (conservative / standard / aggressive + 현재유지)
function buildActionPlans(caseId: string): BncActionPlansPayload {
  const planConservativeId = `${caseId}-plan-conservative`;
  const planStandardId = `${caseId}-plan-standard`;
  const planAggressiveId = `${caseId}-plan-aggressive`;

  return {
    caseId,
    baseline: {
      throughput: 3468,
      avgWaitDay: 10.551,
      deliveryCompliance: 95,
      avgDelayDay: 0.078,
    },
    currentOption: {
      label: '현재상태',
      actionKind: 'baseline',
      title: '현재 유지',
      summary: '조치 없이 현 상태를 유지합니다. 120분 후 WIP 및 대기 시간 추가 악화 예상.',
      confidence: null,
      compositeScore: 0,
      scoreVerdict: 'no_action',
      metrics: [
        { label: '평균 대기', value: '187분', caption: '현재' },
        { label: 'WIP', value: '5 Lot', caption: '현재' },
        { label: 'Wait Ratio', value: '70.0%', caption: '현재' },
        { label: '평균 가동률', value: '79.1%', caption: '현재' },
        { label: '가용 Tool 비율', value: '60.0%', caption: '현재' },
      ],
    },
    compareContext: {
      anchorToolgroup: 'Diffusion_FE_125',
      severity: 'CRITICAL',
      horizonMin: 120,
      generatedAt: '2026-06-14T23:12:51Z',
      naturalForecast: {
        label: '120분 후 악화 예상',
        getsWorse: true,
        metrics: [
          { label: 'WIP', value: '7 Lot', caption: '예측' },
          { label: '평균 대기', value: '233분', caption: '예측' },
        ],
      },
    },
    plans: [
      {
        planId: planStandardId,
        actionLabel: 'standard',
        actionKind: 'REQUEUE_TOOL',
        title: 'Standard — 다수 Lot 재배정 + 긴급 우선처리',
        summary:
          'Diffusion_FE_126/127로 WIP 대부분을 재배정하고 긴급 Lot을 우선 처리합니다. 2건의 유사사례에서 30분 내 KPI 정상화가 확인됐습니다.',
        expectedImpact: 'Q-Time -27.8%, WIP -23.5%, Wait Ratio -57.1%',
        riskText: '다수 Tool recipe/qualification 사전 확인 필요. 재배정 완료까지 약 15분 소요.',
        confidence: 0.91,
        compositeScore: 0.87,
        scoreVerdict: 'significant_improvement',
        recommended: true,
        actionMetadata: { effort: null, scope: 'moderate', reversibility: 'easy' },
        targetToolGroups: ['Diffusion_FE_126', 'Diffusion_FE_127'],
        tradeoffs: ['재배정 준비 시간 약 15분 필요', 'FE_126 recipe 검증 선행 조건'],
        operationItems: [
          'Diffusion_FE_126으로 WIP 3 Lot 재배정',
          '긴급 Lot 우선 처리 큐 지정',
          '30분 후 wait_ratio 재확인',
        ],
        metrics: [
          { label: '평균 대기', before: '187분', after: '135분', delta: '-52분', pctDelta: -27.8, tone: 'positive' },
          { label: 'WIP', before: '5 Lot', after: '4 Lot', delta: '-1 Lot', pctDelta: -23.5, tone: 'positive' },
          { label: 'Wait Ratio', before: '70.0%', after: '30.0%', delta: '-40.0%p', pctDelta: -57.1, tone: 'positive' },
          { label: '평균 가동률', before: '79.1%', after: '75.8%', delta: '-3.3%p', pctDelta: -4.2, tone: 'positive' },
          {
            label: '가용 Tool 비율',
            before: '60.0%',
            after: '72.0%',
            delta: '+12.0%p',
            pctDelta: 20.0,
            tone: 'positive',
          },
        ],
        impactTone: 'positive',
      },
      {
        planId: planConservativeId,
        actionLabel: 'conservative',
        actionKind: 'REQUEUE_TOOL',
        title: 'Conservative — 소수 Lot 재배정',
        summary: 'Diffusion_FE_126으로 소수 Lot만 재배정합니다. 운영 리스크가 낮지만 개선폭이 제한적입니다.',
        expectedImpact: 'Q-Time -8.3%, WIP -5.9%, Wait Ratio -14.3%',
        riskText: '개선 효과가 작아 재발 가능성 있음.',
        confidence: 0.78,
        compositeScore: 0.65,
        scoreVerdict: 'modest_improvement',
        recommended: false,
        actionMetadata: { effort: null, scope: 'narrow', reversibility: 'easy' },
        targetToolGroups: ['Diffusion_FE_126'],
        tradeoffs: ['단기 안정화에 그칠 수 있음', 'Standard 대비 효과 30% 수준'],
        operationItems: ['Diffusion_FE_126으로 WIP 1 Lot 재배정', '60분 후 Q-Time 재확인'],
        metrics: [
          { label: '평균 대기', before: '187분', after: '172분', delta: '-15분', pctDelta: -8.3, tone: 'positive' },
          { label: 'WIP', before: '5 Lot', after: '5 Lot', delta: '0 Lot', pctDelta: -5.9, tone: 'neutral' },
          { label: 'Wait Ratio', before: '70.0%', after: '60.0%', delta: '-10.0%p', pctDelta: -14.3, tone: 'positive' },
          { label: '평균 가동률', before: '79.1%', after: '81.3%', delta: '+2.2%p', pctDelta: 2.8, tone: 'negative' },
          {
            label: '가용 Tool 비율',
            before: '60.0%',
            after: '64.0%',
            delta: '+4.0%p',
            pctDelta: 6.7,
            tone: 'positive',
          },
        ],
        impactTone: 'neutral',
      },
      {
        planId: planAggressiveId,
        actionLabel: 'aggressive',
        actionKind: 'LOT_HOLD',
        title: 'Aggressive — 복수 Lot 보류 + 투입 정지',
        summary: '복수 Lot을 보류하고 투입을 일시 정지합니다. 단기 효과가 가장 크지만 운영 리스크가 높습니다.',
        expectedImpact: 'Q-Time -50.0%, WIP -35.3%, Wait Ratio -71.4%',
        riskText: 'Q-time 조건 미달 Lot 발생 가능. 생산 중단 리스크. 즉시 recipe 검증 필요.',
        confidence: 0.72,
        compositeScore: 0.71,
        scoreVerdict: 'aggressive_improvement',
        recommended: false,
        actionMetadata: { effort: null, scope: 'broad', reversibility: 'hard' },
        targetToolGroups: ['Diffusion_FE_125', 'Diffusion_FE_126'],
        tradeoffs: ['생산 중단 리스크', '복구 어려움 — 롤백 시 추가 지연 발생', 'Recipe 검증 선행 필수'],
        operationItems: [
          'WIP 2 Lot 이상 보류 처리',
          '투입 큐 일시 정지',
          '15분 후 KPI 전체 재확인',
          '개선 없을 시 즉시 롤백',
        ],
        metrics: [
          { label: '평균 대기', before: '187분', after: '94분', delta: '-93분', pctDelta: -50.0, tone: 'positive' },
          { label: 'WIP', before: '5 Lot', after: '3 Lot', delta: '-2 Lot', pctDelta: -35.3, tone: 'positive' },
          { label: 'Wait Ratio', before: '70.0%', after: '20.0%', delta: '-50.0%p', pctDelta: -71.4, tone: 'positive' },
          { label: '평균 가동률', before: '79.1%', after: '72.4%', delta: '-6.7%p', pctDelta: -8.3, tone: 'positive' },
          {
            label: '가용 Tool 비율',
            before: '60.0%',
            after: '80.0%',
            delta: '+20.0%p',
            pctDelta: 33.3,
            tone: 'positive',
          },
        ],
        impactTone: 'positive',
      },
    ],
    recommendation: {
      actionLabel: 'standard',
      actionKind: 'REQUEUE_TOOL',
      reason:
        '2건의 유사사례(DefMet_FE_43, Litho_BE_110)에서 동일 조치로 30분 내 정상화가 확인됐습니다. Conservative는 효과가 부족하고, Aggressive는 생산 중단 리스크가 과도합니다.',
      structured: {
        headline: 'Standard 재배정안 권장 — 30분 내 KPI 정상화 예측',
        primaryReason: '유사사례 2건에서 효과 확인, 시뮬레이션 신뢰도 91%',
        whyNotOthers: {
          conservative: '개선폭 부족 (Q-Time -8.3% 수준), 재발 가능성 있음',
          aggressive: '운영 리스크 과도 (Q-time 미달, 생산 중단 리스크)',
        },
        caveats: ['재배정 준비 15분 소요', 'FE_126 recipe 사전 검증 필수'],
        confidenceLevel: 'HIGH',
        immediateActions: [
          'Diffusion_FE_126으로 WIP 3 Lot 재배정 요청',
          '긴급 Lot(CQT 임박) 우선 처리 큐 지정',
          '30분 후 wait_ratio 재확인 (목표: 30% 이하)',
        ],
        monitoringKpis: ['wait_ratio (목표 30% 이하)', 'WIP (목표 4 Lot 이하)', 'Q-Time (목표 140분 이하)'],
        rollbackCondition: '30분 내 WIP 감소 없거나 wait_ratio 유지 시 보류 해제 후 Aggressive 검토',
        recommendationStatus: 'AI 추천',
      },
    },
    decisionInfo: {
      decisionStatus: 'clear_winner',
      topLabel: 'standard',
      equivalentSet: [],
      tiebreakerUsed: null,
      decisionCaveat: '시뮬레이션 결과는 잠정치입니다. 현장 검증 후 승인하세요.',
    },
    hitlStatus: {
      hasDecision: false,
      latestDecision: null,
      selectedPlanId: null,
      comment: null,
    },
    ragEvidence: {
      commonHits: DIFFUSION_FE_125_CAUSE.ragSimilarCases,
      perPlan: {
        [planConservativeId]: {
          candidateSummary: '보수적 재배정안. 유사사례에서 단기 안전 효과가 확인되나 개선폭이 제한적입니다.',
          riskLevel: 'low',
          evidenceStrength: 'moderate',
          effectOutlook: '소폭 개선 (Q-Time -8%), 재발 가능성 있음',
          claims: ['CMP_BE_12에서 유사 소폭 조치 후 60분 내 정상화'],
        },
        [planStandardId]: {
          candidateSummary:
            '표준 재배정안. 2건의 유사사례에서 30분 내 KPI 정상화 근거가 있으며 시뮬레이션 신뢰도가 가장 높습니다.',
          riskLevel: 'medium',
          evidenceStrength: 'strong',
          effectOutlook: '30분 내 KPI 정상화 예측',
          claims: [
            'DefMet_FE_43에서 동일 조치 후 WIP -3 Lot, Q-Time -45분 달성',
            'Litho_BE_110에서 wait_ratio 57% 감소 확인',
          ],
        },
        [planAggressiveId]: {
          candidateSummary:
            '공격적 투입 조정. 단기 효과는 가장 크지만 설비 recipe 검증과 생산 중단 리스크 관리가 필요합니다.',
          riskLevel: 'high',
          evidenceStrength: 'moderate',
          effectOutlook: '단기 KPI 최대 개선, 운영 리스크 높음',
          claims: ['유사사례에서 동일 수준 조치 후 초기 효과 확인됐으나 재발 사례 1건 있음'],
        },
      },
    },
  };
}

// 제공된 report_DE_FE_1_20260614_231251.json 기반 ReportV1 목 데이터
const DIFFUSION_FE_125_REPORT_V1: ReportV1 = {
  schema_version: 'report/1.0',
  meta: {
    toolgroup: 'Diffusion_FE_125',
    process_name: 'FE Diffusion 125',
    severity: 'CRITICAL',
    severity_token: 'critical',
    severity_priority: 1,
    detected_at: '2026-06-14T09:56:57Z',
    generated_at: '2026-06-14T23:12:51Z',
    snapshot_time: 1749948977,
    horizon_min: 120,
    schema_version: 'report/1.0',
  },
  approval: {
    status: '대기 중',
    status_token: 'pending',
    approver_name: '',
    approver_role: '',
    approved_at: '',
    comment: '',
    rejection_reason: null,
    selected_label: null,
  },
  risk: {
    score: 9.551,
    score_unit: '점',
    score_threshold_state: 'danger',
    composite_score: 0.9551,
    probability: 0.9941,
  },
  confidence: {
    level: 'HIGH',
    level_token: 'high',
    needs_more_data: false,
    g_star_probability: 0.9967,
  },
  if_no_action: {
    available: true,
    will_get_worse: true,
    horizon_min: 120,
    kpi_changes: [
      { kpi: 'wip', unit: 'lots', now: 5, after: 7, delta: 2, pct_change: 40.0, reliability_token: 'HIGH' },
      { kpi: 'q_time_min', unit: 'min', now: 187, after: 233, delta: 46, pct_change: 24.6, reliability_token: 'HIGH' },
      {
        kpi: 'wait_ratio',
        unit: '',
        now: 0.7,
        after: 0.85,
        delta: 0.15,
        pct_change: 21.4,
        reliability_token: 'MEDIUM',
      },
    ],
  },
  bottleneck_kpis: [
    {
      key: 'wip',
      label: 'WIP',
      value: 5,
      unit: 'lots',
      threshold_state: 'danger',
      prev_value: 3,
      delta: 2,
      pct_change: 66.7,
    },
    {
      key: 'q_time_min',
      label: '평균 대기',
      value: 187,
      unit: 'min',
      threshold_state: 'danger',
      prev_value: 120,
      delta: 67,
      pct_change: 55.8,
    },
    {
      key: 'wait_ratio',
      label: 'Wait Ratio',
      value: 0.7,
      unit: '',
      threshold_state: 'danger',
      prev_value: 0.45,
      delta: 0.25,
      pct_change: 55.6,
    },
    {
      key: 'utilization_avg',
      label: '평균 가동률',
      value: 0.7914,
      unit: '',
      threshold_state: 'warning',
      prev_value: 0.65,
      delta: 0.1414,
      pct_change: 21.4,
    },
    {
      key: 'available_tool_ratio',
      label: '가용 Tool 비율',
      value: 0.6,
      unit: '',
      threshold_state: 'warning',
      prev_value: 0.72,
      delta: -0.12,
      pct_change: -16.7,
    },
  ],
  data_quality: {
    status: 'ok',
    warnings: [],
  },
  cause: {
    summary: '설비 포화(max_util 79.1%)와 WIP 누적이 주원인. 대기 누적·공급 부족은 근거 부족으로 기각됨.',
    primary: {
      category: '설비_포화',
      feature: 'max_util',
      confidence: 'HIGH',
      confidence_token: 'high',
      reasoning:
        'SHAP 기여 71.5%, G* 통계 확인(proba 0.997), 가동률 급등 추세 유의(r2=0.834). max_util_delta_120(+1.885)과 함께 설비 포화가 주원인으로 확인됨.',
    },
    secondary_categories: ['WIP_누적'],
    categories: [
      {
        name: '설비_포화',
        features: ['max_util', 'max_util_delta_120', 'utilization_avg'],
        shap_share_pct: 80.5,
        n_trend_significant: 1,
        upstream_match: false,
        g_star_confirmed: true,
        total_score: 0.9551,
        confidence: 'HIGH',
        confidence_token: 'high',
      },
      {
        name: 'WIP_누적',
        features: ['wip'],
        shap_share_pct: 19.5,
        n_trend_significant: 1,
        upstream_match: true,
        g_star_confirmed: false,
        total_score: 0.4249,
        confidence: 'MEDIUM',
        confidence_token: 'medium',
      },
      {
        name: '대기_누적',
        features: ['wait_ratio', 'q_time_min'],
        shap_share_pct: 0,
        n_trend_significant: 0,
        upstream_match: true,
        g_star_confirmed: false,
        total_score: 0.08,
        confidence: 'LOW',
        confidence_token: 'low',
      },
      {
        name: '공급_부족',
        features: ['available_tool_ratio'],
        shap_share_pct: 0,
        n_trend_significant: 0,
        upstream_match: true,
        g_star_confirmed: false,
        total_score: 0.08,
        confidence: 'LOW',
        confidence_token: 'low',
      },
    ],
    shap_top: [
      {
        rank: 1,
        feature: 'max_util_delta_120',
        value: 0.0,
        shap: 1.8853,
        contribution_pct: 38.7,
        direction_token: 'bottleneck',
      },
      { rank: 2, feature: 'max_util', value: 1.0, shap: 1.6214, contribution_pct: 33.3, direction_token: 'bottleneck' },
      { rank: 3, feature: 'wip', value: 5.0, shap: 0.9499, contribution_pct: 19.5, direction_token: 'bottleneck' },
      {
        rank: 4,
        feature: 'utilization_avg',
        value: 0.7914,
        shap: 0.4173,
        contribution_pct: 8.6,
        direction_token: 'bottleneck',
      },
    ],
    trend_series: {
      time_labels: ['-120m', '-90m', '-60m', '-30m', 'now'],
      time_offsets_min: [-120, -90, -60, -30, 0],
      features: {
        wip: { values: [2, 3, 3, 4, 5], slope_per_hour: 0.5143, r2: 0.631, significant: true },
        utilization_avg: {
          values: [0.62, 0.65, 0.7, 0.75, 0.79],
          slope_per_hour: 0.0743,
          r2: 0.834,
          significant: true,
        },
        q_time_min: { values: [130, 145, 160, 175, 187], slope_per_hour: 1.3957, r2: 0.429, significant: false },
      },
    },
    upstream_suspects: ['WE_FE_84', 'DE_FE_86'],
    consensus_axes: {
      shap_supports: true,
      trend_supports: true,
      upstream_supports: false,
      g_star_supports: true,
      axes_agreed_count: 3,
    },
    g_star: {
      confirmed: true,
      probability: 0.9967,
      monte_carlo: { n_total: 100, n_alarm: 97, alarm_ratio_pct: 97.0 },
      upstream_confirmed_toolgroups: [],
      significant_kpis: ['utilization_avg'],
    },
  },
  diffusion: {
    bottleneck_location: 'Diffusion_FE_125',
    diffusion_path: ['Diffusion_FE_125', 'Litho_FE_130', 'CMP_FE_140'],
    high_impact_processes: [
      {
        toolgroup: 'Diffusion_FE_125',
        utilization_pct: 79.14,
        wait_ratio: 0.7,
        wip: 5,
        impact_score: 0.9551,
        data_quality_flags: [],
      },
      {
        toolgroup: 'Litho_FE_130',
        utilization_pct: 68.3,
        wait_ratio: 0.45,
        wip: 3,
        impact_score: 0.612,
        data_quality_flags: [],
      },
      {
        toolgroup: 'CMP_FE_140',
        utilization_pct: 55.2,
        wait_ratio: 0.3,
        wip: 2,
        impact_score: 0.38,
        data_quality_flags: [],
      },
    ],
    low_impact_processes: [],
    forward_simulation: {
      available: true,
      horizon_min: 120,
      results: [
        {
          toolgroup: 'Diffusion_FE_125',
          q_time_min_future: 233,
          wait_ratio_future: 0.85,
          wip_future: 7,
          is_bottleneck_predicted: true,
        },
        {
          toolgroup: 'Litho_FE_130',
          q_time_min_future: 78,
          wait_ratio_future: 0.55,
          wip_future: 4,
          is_bottleneck_predicted: false,
        },
      ],
    },
    line_stop_expected_min: 0,
    risk_level: 'HIGH',
    risk_level_token: 'high',
  },
  actions: {
    available: true,
    candidates: [
      {
        label: '현재상태',
        kind: 'baseline',
        is_baseline: true,
        is_approved: false,
        description: '조치 없이 현 상태를 유지합니다.',
        target_toolgroups: [],
        params: null,
        kpi_impact: [
          {
            kpi: 'wip',
            unit: 'lots',
            now: 5,
            after: 5,
            delta: 0,
            pct_change: 0,
            verdict: 'no_change',
            verdict_token: 'no_change',
            confidence: 1,
            ci_low: 0,
            ci_high: 0,
            ci_width: 0,
            paired_t_p: null,
            significant: null,
          },
          {
            kpi: 'q_time_min',
            unit: 'min',
            now: 187,
            after: 187,
            delta: 0,
            pct_change: 0,
            verdict: 'no_change',
            verdict_token: 'no_change',
            confidence: 1,
            ci_low: 0,
            ci_high: 0,
            ci_width: 0,
            paired_t_p: null,
            significant: null,
          },
          {
            kpi: 'wait_ratio',
            unit: '',
            now: 0.7,
            after: 0.7,
            delta: 0,
            pct_change: 0,
            verdict: 'no_change',
            verdict_token: 'no_change',
            confidence: 1,
            ci_low: 0,
            ci_high: 0,
            ci_width: 0,
            paired_t_p: null,
            significant: null,
          },
          {
            kpi: 'utilization_avg',
            unit: '',
            now: 0.7914,
            after: 0.7914,
            delta: 0,
            pct_change: 0,
            verdict: 'no_change',
            verdict_token: 'no_change',
            confidence: 1,
            ci_low: 0,
            ci_high: 0,
            ci_width: 0,
            paired_t_p: null,
            significant: null,
          },
          {
            kpi: 'available_tool_ratio',
            unit: '',
            now: 0.6,
            after: 0.6,
            delta: 0,
            pct_change: 0,
            verdict: 'no_change',
            verdict_token: 'no_change',
            confidence: 1,
            ci_low: 0,
            ci_high: 0,
            ci_width: 0,
            paired_t_p: null,
            significant: null,
          },
        ],
        operational: { effort: 0, effort_max: 5, scope: 'none', reversibility: 'n/a' },
        simulation: { paired_n: 0, confidence: null, verdict: 'no_action' },
        composite_score: 0,
        tradeoffs: [],
      },
      {
        label: 'conservative',
        kind: 'REQUEUE_TOOL',
        is_baseline: false,
        is_approved: false,
        description: 'Diffusion_FE_126으로 소수 Lot 재배정',
        target_toolgroups: ['Diffusion_FE_126'],
        params: null,
        kpi_impact: [
          {
            kpi: 'wip',
            unit: 'lots',
            now: 5,
            after: 4.7,
            delta: -0.3,
            pct_change: -5.9,
            verdict: 'modest_improvement',
            verdict_token: 'modest',
            confidence: 0.78,
            ci_low: -0.6,
            ci_high: 0,
            ci_width: 0.6,
            paired_t_p: 0.12,
            significant: false,
          },
          {
            kpi: 'q_time_min',
            unit: 'min',
            now: 187,
            after: 171.5,
            delta: -15.5,
            pct_change: -8.3,
            verdict: 'modest_improvement',
            verdict_token: 'modest',
            confidence: 0.78,
            ci_low: -25,
            ci_high: -5,
            ci_width: 20,
            paired_t_p: 0.08,
            significant: false,
          },
          {
            kpi: 'wait_ratio',
            unit: '',
            now: 0.7,
            after: 0.6,
            delta: -0.1,
            pct_change: -14.3,
            verdict: 'modest_improvement',
            verdict_token: 'modest',
            confidence: 0.78,
            ci_low: -0.18,
            ci_high: -0.02,
            ci_width: 0.16,
            paired_t_p: 0.06,
            significant: false,
          },
          {
            kpi: 'utilization_avg',
            unit: '',
            now: 0.7914,
            after: 0.8135,
            delta: 0.022,
            pct_change: 2.8,
            verdict: 'slight_worsening',
            verdict_token: 'slight_worsening',
            confidence: 0.78,
            ci_low: 0,
            ci_high: 0.05,
            ci_width: 0.05,
            paired_t_p: 0.15,
            significant: false,
          },
          {
            kpi: 'available_tool_ratio',
            unit: '',
            now: 0.6,
            after: 0.64,
            delta: 0.04,
            pct_change: 6.7,
            verdict: 'modest_improvement',
            verdict_token: 'modest',
            confidence: 0.78,
            ci_low: 0,
            ci_high: 0.08,
            ci_width: 0.08,
            paired_t_p: 0.1,
            significant: false,
          },
        ],
        operational: { effort: 1, effort_max: 5, scope: 'narrow', reversibility: 'easy' },
        simulation: { paired_n: 4, confidence: 0.78, verdict: 'modest_improvement' },
        composite_score: 0.65,
        tradeoffs: ['단기 안정화에 그칠 수 있음', 'Standard 대비 효과 30% 수준'],
      },
      {
        label: 'standard',
        kind: 'REQUEUE_TOOL',
        is_baseline: false,
        is_approved: false,
        description: '다수 Lot 재배정 + 긴급 Lot 우선처리',
        target_toolgroups: ['Diffusion_FE_126', 'Diffusion_FE_127'],
        params: null,
        kpi_impact: [
          {
            kpi: 'wip',
            unit: 'lots',
            now: 5,
            after: 3.8,
            delta: -1.2,
            pct_change: -23.5,
            verdict: 'significant_improvement',
            verdict_token: 'significant',
            confidence: 0.91,
            ci_low: -1.8,
            ci_high: -0.6,
            ci_width: 1.2,
            paired_t_p: 0.003,
            significant: true,
          },
          {
            kpi: 'q_time_min',
            unit: 'min',
            now: 187,
            after: 135,
            delta: -52,
            pct_change: -27.8,
            verdict: 'significant_improvement',
            verdict_token: 'significant',
            confidence: 0.91,
            ci_low: -65,
            ci_high: -39,
            ci_width: 26,
            paired_t_p: 0.001,
            significant: true,
          },
          {
            kpi: 'wait_ratio',
            unit: '',
            now: 0.7,
            after: 0.3,
            delta: -0.4,
            pct_change: -57.1,
            verdict: 'significant_improvement',
            verdict_token: 'significant',
            confidence: 0.91,
            ci_low: -0.5,
            ci_high: -0.3,
            ci_width: 0.2,
            paired_t_p: 0.001,
            significant: true,
          },
          {
            kpi: 'utilization_avg',
            unit: '',
            now: 0.7914,
            after: 0.758,
            delta: -0.033,
            pct_change: -4.2,
            verdict: 'modest_improvement',
            verdict_token: 'modest',
            confidence: 0.91,
            ci_low: -0.06,
            ci_high: -0.01,
            ci_width: 0.05,
            paired_t_p: 0.02,
            significant: true,
          },
          {
            kpi: 'available_tool_ratio',
            unit: '',
            now: 0.6,
            after: 0.72,
            delta: 0.12,
            pct_change: 20.0,
            verdict: 'significant_improvement',
            verdict_token: 'significant',
            confidence: 0.91,
            ci_low: 0.06,
            ci_high: 0.18,
            ci_width: 0.12,
            paired_t_p: 0.005,
            significant: true,
          },
        ],
        operational: { effort: 2, effort_max: 5, scope: 'moderate', reversibility: 'easy' },
        simulation: { paired_n: 8, confidence: 0.91, verdict: 'significant_improvement' },
        composite_score: 0.87,
        tradeoffs: ['재배정 준비 15분 소요', 'FE_126 recipe 사전 검증 필수'],
      },
      {
        label: 'aggressive',
        kind: 'LOT_HOLD',
        is_baseline: false,
        is_approved: false,
        description: '복수 Lot 보류 + 투입 정지',
        target_toolgroups: ['Diffusion_FE_125', 'Diffusion_FE_126'],
        params: null,
        kpi_impact: [
          {
            kpi: 'wip',
            unit: 'lots',
            now: 5,
            after: 3.2,
            delta: -1.8,
            pct_change: -35.3,
            verdict: 'aggressive_improvement',
            verdict_token: 'aggressive',
            confidence: 0.72,
            ci_low: -2.5,
            ci_high: -1.1,
            ci_width: 1.4,
            paired_t_p: 0.01,
            significant: true,
          },
          {
            kpi: 'q_time_min',
            unit: 'min',
            now: 187,
            after: 94,
            delta: -93,
            pct_change: -50.0,
            verdict: 'aggressive_improvement',
            verdict_token: 'aggressive',
            confidence: 0.72,
            ci_low: -110,
            ci_high: -76,
            ci_width: 34,
            paired_t_p: 0.008,
            significant: true,
          },
          {
            kpi: 'wait_ratio',
            unit: '',
            now: 0.7,
            after: 0.2,
            delta: -0.5,
            pct_change: -71.4,
            verdict: 'aggressive_improvement',
            verdict_token: 'aggressive',
            confidence: 0.72,
            ci_low: -0.6,
            ci_high: -0.4,
            ci_width: 0.2,
            paired_t_p: 0.007,
            significant: true,
          },
          {
            kpi: 'utilization_avg',
            unit: '',
            now: 0.7914,
            after: 0.724,
            delta: -0.067,
            pct_change: -8.3,
            verdict: 'modest_improvement',
            verdict_token: 'modest',
            confidence: 0.72,
            ci_low: -0.1,
            ci_high: -0.03,
            ci_width: 0.07,
            paired_t_p: 0.03,
            significant: true,
          },
          {
            kpi: 'available_tool_ratio',
            unit: '',
            now: 0.6,
            after: 0.8,
            delta: 0.2,
            pct_change: 33.3,
            verdict: 'significant_improvement',
            verdict_token: 'significant',
            confidence: 0.72,
            ci_low: 0.1,
            ci_high: 0.3,
            ci_width: 0.2,
            paired_t_p: 0.02,
            significant: true,
          },
        ],
        operational: { effort: 4, effort_max: 5, scope: 'broad', reversibility: 'hard' },
        simulation: { paired_n: 5, confidence: 0.72, verdict: 'aggressive_improvement' },
        composite_score: 0.71,
        tradeoffs: ['생산 중단 리스크', '복구 어려움 — 롤백 시 추가 지연 발생', 'Recipe 검증 선행 필수'],
      },
    ],
    approved_label: null,
    decision_status: '대기 중',
    decision_status_token: 'pending',
    equivalent_set: [],
    tiebreaker_used: null,
    decision_caveat: '시뮬레이션 결과는 잠정치입니다. 현장 검증 후 승인하세요.',
    recommendation: {
      headline: 'Standard 재배정안 권장 — 30분 내 KPI 정상화 예측',
      primary_reason: '유사사례 2건에서 효과 확인, 시뮬레이션 신뢰도 91%',
      confidence_level: 'HIGH',
      confidence_token: 'high',
      tradeoffs: ['재배정 준비 15분 소요', 'FE_126 recipe 사전 검증 필수'],
      why_not_others: [
        { label: 'conservative', reason: '개선폭 부족 (Q-Time -8.3% 수준), 재발 가능성 있음' },
        { label: 'aggressive', reason: '운영 리스크 과도 (Q-time 미달, 생산 중단 리스크)' },
      ],
      caveats: ['재배정 준비 15분 소요', 'FE_126 recipe 사전 검증 필수'],
      tiebreaker_chain: [],
      selected_by: 'composite_score',
    },
    playbook: {
      available: true,
      immediate_actions: [
        { order: 1, text: 'Diffusion_FE_126으로 WIP 3 Lot 재배정 요청' },
        { order: 2, text: '긴급 Lot(CQT 임박) 우선 처리 큐 지정' },
        { order: 3, text: '30분 후 wait_ratio 재확인 (목표: 30% 이하)' },
      ],
      monitoring: [
        { kpi: 'wait_ratio', target: 0.3, unit: '', check_after_min: 30 },
        { kpi: 'wip', target: 4, unit: 'lots', check_after_min: 60 },
        { kpi: 'q_time_min', target: 140, unit: 'min', check_after_min: 60 },
      ],
      rollback_condition: '30분 내 WIP 감소 없거나 wait_ratio 유지 시 보류 해제 후 Aggressive 검토',
    },
  },
  sections: {
    summary: 'Diffusion_FE_125에서 Critical 병목 감지. 설비 포화 (max_util 79.1%)가 주원인. Standard 재배정안 권장.',
    cause: '설비_포화 (SHAP 80.5%, G* 확인) → WIP_누적 (SHAP 19.5%)',
    action: 'standard: Lot 재배정 → Q-Time -27.8%, WIP -23.5%, Wait Ratio -57.1%',
  },
  rendered: {
    markdown: '# Diffusion_FE_125 병목 대응 보고서\n\n병목 확률 99.4%, 위험도 CRITICAL. Standard 재배정 권장.',
  },
  rag_evidence: {
    common_hits: [
      {
        case_id: 'DefMet_FE_43',
        score: 0.94,
        tg_code: 'FE-DIFF-125',
        cause_summary: '동일 TG 포화, REQUEUE 후 30분 내 해소',
        report_title: '2026-06 확산로 포화 대응',
      },
      {
        case_id: 'Litho_BE_110',
        score: 0.87,
        tg_code: 'BE-LITHO-110',
        cause_summary: 'WIP 급증, LOT_HOLD 안정화 (Q-Time -40분)',
        report_title: '2026-05 리소 WIP 급등',
      },
      {
        case_id: 'CMP_BE_12',
        score: 0.72,
        tg_code: 'BE-CMP-12',
        cause_summary: '가용률 저하 패턴, 표준 재배정으로 60분 내 정상화',
        report_title: '2026-05 CMP 가용률 저하',
      },
    ],
  },
};

export const MOCK_BNC_CAUSE_ANALYSIS: Record<string, BncCauseAnalysis> = {
  [DIFFUSION_FE_125_CASE_ID]: DIFFUSION_FE_125_CAUSE,
};

export const MOCK_BNC_ACTION_PLANS: Record<string, BncActionPlansPayload> = {
  [DIFFUSION_FE_125_CASE_ID]: buildActionPlans(DIFFUSION_FE_125_CASE_ID),
};

export const MOCK_BNC_REPORTS: Record<string, BncReportPayload> = {
  [DIFFUSION_FE_125_CASE_ID]: {
    reportId: `report-${DIFFUSION_FE_125_CASE_ID}`,
    caseId: DIFFUSION_FE_125_CASE_ID,
    summary:
      'Diffusion_FE_125에서 Critical 병목이 감지되었고(probability 99.4%), 위험 Lot 76개·CT 증가 259.3분이 예측됨. 주요 원인은 설비_포화(max_util). Standard 재배정안 권장.',
    rootCauseText:
      '주요 원인은 설비_포화(max_util, max_util_delta_120, utilization_avg)이며, 보조 원인으로 WIP_누적이 확인됨. 대기_누적·공급_부족은 근거가 약해 기각됨.',
    actionComparisonText: 'Standard 재배정안 권장 (신뢰도 91%). Q-Time -27.8%, WIP -23.5%, Wait Ratio -57.1%.',
    timeline: [
      { time: '2026-06-14T09:56:57Z', event: 'Diffusion_FE_125 병목 감지 (Critical, prob 99.4%)' },
      { time: '2026-06-14T10:02:00Z', event: 'SHAP/트렌드/업스트림 기반 원인 분석 완료 (설비_포화)' },
      { time: '2026-06-14T23:12:51Z', event: '대응안 비교 분석 완료 — standard 권장 (sim 신뢰도 91%)' },
    ],
    hasPdf: false,
    generatedAt: '2026-06-14T23:12:51Z',
    regeneratedCount: 0,
    qdrantIndexed: false,
    reportV1: DIFFUSION_FE_125_REPORT_V1,
    finalReport: MOCK_FINAL_BOTTLENECK_REPORT,
  },
};
