import type { BncActionPlansPayload, BncCauseAnalysis, BncReportPayload } from '@/types/bnc';
import type { ReportV1 } from '@/types/report';

const DE_FE_1_CASE_ID = 'case-de-fe-1-3780';
const DETECTED_AT = '2026-06-14T14:12:00Z';
const GENERATED_AT = '2026-06-14T14:12:46Z';

const RAG_SIMILAR_CASES = [
  {
    caseId: 'demo-3780-standard',
    score: 0.96,
    tgCode: 'DE_FE_1 + Diffusion_FE_125',
    reportTitle: 'DE_FE_1 + Diffusion_FE_125 standard 복합 대응 합성 사례',
    summary:
      'Release Interval +22%, Product_3/Product_4 우선순위 상향으로 두 TG의 WIP와 대기를 균형 있게 낮춘 사례입니다.',
  },
  {
    caseId: 'demo-3780-conservative',
    score: 0.88,
    tgCode: 'DE_FE_1 + Diffusion_FE_125',
    reportTitle: 'DE_FE_1 + Diffusion_FE_125 conservative 복합 대응 합성 사례',
    summary: 'Release Interval +15%는 운영 리스크가 낮지만 복합 병목 회복 폭이 제한적인 것으로 기록됐습니다.',
  },
  {
    caseId: 'demo-3780-aggressive',
    score: 0.84,
    tgCode: 'DE_FE_1 + Diffusion_FE_125',
    reportTitle: 'DE_FE_1 + Diffusion_FE_125 aggressive 복합 대응 합성 사례',
    summary:
      'Release Interval +28%와 SuperHotLot 적용은 대기 개선이 빠르지만 Diffusion_FE_125 WIP 편중과 가용성 저하가 동반됐습니다.',
  },
];

const DE_FE_1_CAUSE: BncCauseAnalysis = {
  caseId: DE_FE_1_CASE_ID,
  analysisId: `analysis-${DE_FE_1_CASE_ID}`,
  predictionSummary: {
    bottleneckProb: 0.9958,
    riskGrade: 'CRITICAL',
    maxWipCount: 10,
    maxUtilizationRate: 0.9943,
  },
  diffusion: {
    affectedToolGroups: [{ tgId: 'tg-diffusion-fe-125', tgName: 'Diffusion_FE_125', areaName: 'Diffusion' }],
  },
  causeSummary: [
    {
      tgId: 'tg-de-fe-1',
      tgName: 'DE_FE_1',
      bottleneckCauseType: '설비_포화',
      utilRate: 0.9943,
      waitingLots: 10,
      setupRatio: 0.25,
      slope: 0.1377,
    },
  ],
  shapFeatures: [
    {
      feature: 'max_util_delta_120',
      label: '최대 가동률 120분 변화',
      importance: 0.342,
      rank: 1,
      direction: '병목 쪽으로 기여(+)',
      shapValue: 1.8051,
      kpiValue: 0,
      contributionPct: 34.2,
    },
    {
      feature: 'max_util',
      label: '최대 가동률',
      importance: 0.339,
      rank: 2,
      direction: '병목 쪽으로 기여(+)',
      shapValue: 1.7895,
      kpiValue: 1,
      contributionPct: 33.9,
    },
    {
      feature: 'utilization_avg',
      label: '평균 가동률',
      importance: 0.183,
      rank: 3,
      direction: '병목 쪽으로 기여(+)',
      shapValue: 0.967,
      kpiValue: 0.9943,
      contributionPct: 18.3,
    },
    {
      feature: 'wip',
      label: 'WIP',
      importance: 0.135,
      rank: 4,
      direction: '병목 쪽으로 기여(+)',
      shapValue: 0.7104,
      kpiValue: 10,
      contributionPct: 13.5,
    },
  ],
  trendInsights: [
    {
      feature: 'q_time_min',
      label: '평균 대기시간',
      slopePerHour: 16.714,
      values: [0, 0, 22.24, 63.77, 76.22, 62.96],
      r2: 0.831,
      significant: true,
    },
    {
      feature: 'wip',
      label: 'WIP',
      slopePerHour: 1.7143,
      values: [4, 4, 10, 13, 13, 10],
      r2: 0.6122,
      significant: true,
    },
    {
      feature: 'utilization_avg',
      label: '평균 가동률',
      slopePerHour: 0.1377,
      values: [0.3389, 0.5, 0.8875, 1, 0.9761, 0.9943],
      r2: 0.7947,
      significant: true,
    },
  ],
  ragSimilarCases: RAG_SIMILAR_CASES,
  modelPerformance: {
    accuracy: 0.923,
    f1Score: 0.891,
    featureCount: 19,
  },
  judgment: {
    primaryCategory: '설비_포화',
    primaryCause: 'max_util',
    primaryConfidence: 'HIGH',
    primaryReasoning:
      '설비_포화가 total score 1.015로 가장 높고 SHAP 기여도도 86.5%로 압도적입니다. max_util_delta_120, max_util, utilization_avg가 모두 병목 방향으로 기여하며 utilization_avg는 Trend★ +0.138/h로 악화 추세입니다.',
    secondaryCauses: ['WIP_누적'],
    dismissed: ['대기_누적', '공급_부족'],
    dismissedReason:
      '대기_누적과 공급_부족은 score가 각각 0.230, 0.080으로 낮고 SHAP 기여도도 0.0%라 주원인으로 보기 어렵습니다.',
    causeSummary:
      '[주요 원인] 설비_포화(max_util 중심)로 인한 병목이 핵심입니다. [악화 추세] utilization_avg가 Trend★ +0.138/h, WIP가 Trend★ +1.714/h로 증가 중입니다. [업스트림] DE_FE_86에서 WIP 과공급 부담이 동반됩니다.',
  },
  causeCategories: [
    {
      name: '설비_포화',
      features: ['max_util', 'max_util_delta_120', 'utilization_avg'],
      shapSharePct: 86.5,
      nTrendSignificant: 1,
      upstreamMatch: false,
      gStarConfirmed: false,
      totalScore: 1.0153,
      confidence: 'HIGH',
    },
    {
      name: 'WIP_누적',
      features: ['wip'],
      shapSharePct: 13.5,
      nTrendSignificant: 1,
      upstreamMatch: true,
      gStarConfirmed: false,
      totalScore: 0.3647,
      confidence: 'MEDIUM',
    },
    {
      name: '대기_누적',
      features: ['wait_ratio', 'q_time_min'],
      shapSharePct: 0,
      nTrendSignificant: 1,
      upstreamMatch: true,
      gStarConfirmed: false,
      totalScore: 0.23,
      confidence: 'LOW',
    },
    {
      name: '공급_부족',
      features: ['available_tool_ratio'],
      shapSharePct: 0,
      nTrendSignificant: 0,
      upstreamMatch: true,
      gStarConfirmed: false,
      totalScore: 0.08,
      confidence: 'LOW',
    },
  ],
  upstreamSuspects: ['DE_FE_86'],
  gStar: {
    confirmed: false,
    proba: 0.6867,
    nTotal: 106,
    nAlarm: 4,
    toolgroups: [],
    sigKpis: [
      { kpi: 'utilization_avg', deltaMean: 0.006, pAdjusted: 1, significant: false },
      { kpi: 'wip', deltaMean: 2, pAdjusted: 1, significant: false },
      { kpi: 'wait_ratio', deltaMean: 0.25, pAdjusted: 1, significant: false },
    ],
    upstreamConfirmed: ['DE_FE_86'],
  },
  simForecast: {
    t0: 0,
    tFuture: 120,
    getsWorse: true,
    kpiDeltas: [
      { kpi: 'q_time_min', now: 62.96, future: 96.39, delta: 33.43, pctChange: 53.1, reliability: 'HIGH' },
      { kpi: 'wip', now: 10, future: 12, delta: 2, pctChange: 20, reliability: 'HIGH' },
      { kpi: 'wait_ratio', now: 0.25, future: 0.5, delta: 0.25, pctChange: 100, reliability: 'HIGH' },
      { kpi: 'utilization_avg', now: 0.9943, future: 1, delta: 0.0057, pctChange: 0.6, reliability: 'MED' },
    ],
  },
  forwardForecastText:
    '무대응 120분 후 DE_FE_1 q_time_min 96.39분, WIP 12 Lot, wait_ratio 0.50으로 악화되고 Diffusion_FE_125도 WIP 18 Lot까지 누적될 것으로 예측됩니다.',
  createdAt: '2026-06-14T14:12:10Z',
};

function buildActionPlans(caseId: string): BncActionPlansPayload {
  const planConservativeId = `${caseId}-plan-conservative`;
  const planStandardId = `${caseId}-plan-standard`;
  const planAggressiveId = `${caseId}-plan-aggressive`;

  return {
    caseId,
    baseline: {
      throughput: 3468,
      avgWaitDay: 0.0437,
      deliveryCompliance: 95,
      avgDelayDay: 0.078,
    },
    currentOption: {
      label: '현재상태',
      actionKind: 'NO_ACTION',
      title: '현재 유지',
      summary: '조치 없이 현 상태를 유지하면 120분 후 DE_FE_1과 Diffusion_FE_125 모두 WIP와 대기가 악화됩니다.',
      confidence: null,
      compositeScore: 0,
      scoreVerdict: 'no_action',
      metrics: [
        { label: '평균 대기', value: '62.96분', caption: '현재' },
        { label: 'WIP', value: '10 Lot', caption: '현재' },
        { label: 'Wait Ratio', value: '0.25', caption: '현재' },
        { label: '평균 가동률', value: '99.4%', caption: '현재' },
        { label: '가용 Tool 비율', value: '100.0%', caption: '현재' },
      ],
    },
    compareContext: {
      anchorToolgroup: 'DE_FE_1',
      targetToolgroups: ['DE_FE_1', 'Diffusion_FE_125'],
      severity: 'CRITICAL',
      horizonMin: 120,
      generatedAt: GENERATED_AT,
      naturalForecast: {
        label: '2h 자연 진행: 악화 예상',
        getsWorse: true,
        metrics: [
          { label: 'DE_FE_1 WIP', value: '12 Lot', caption: '무대응 120분' },
          { label: 'Diffusion WIP', value: '18 Lot', caption: '무대응 120분' },
          { label: 'DE_FE_1 Q-time', value: '96.39분', caption: '무대응 120분' },
        ],
      },
      causeSummary: DE_FE_1_CAUSE.judgment?.causeSummary,
      upstreamSuspects: ['DE_FE_86'],
      cascade: {
        affectedToolgroups: ['Diffusion_FE_125'],
        ctIncreaseMin: 1670,
        atRiskLots: 12,
        capacityStressScore: 0.8031,
        impactScore: 0.6867,
      },
    },
    plans: [
      {
        planId: planStandardId,
        actionLabel: 'standard',
        actionKind: 'DISPATCH_RULE_OVERRIDE',
        title: 'standard',
        summary:
          'fab-wide로 Release Interval을 22% 조정하고 Product_3/Product_4 우선순위를 20으로 올려 DE_FE_1부터 Diffusion_FE_125까지 동일 룰을 전파합니다.',
        expectedImpact: 'q_time -16.26분, WIP -4.0, wait_ratio -0.32, utilization_avg -0.12',
        riskText:
          'Diffusion_FE_125의 available_tool_ratio 악화를 피하면서 DE_FE_1 WIP와 대기를 동시에 낮추는 균형안입니다.',
        confidence: 0.99,
        compositeScore: 0.651,
        scoreVerdict: 'clear_winner',
        recommended: true,
        actionMetadata: { effort: 2, scope: 'fab-wide', reversibility: 'easy' },
        targetToolGroups: ['DE_FE_1', 'Diffusion_FE_125'],
        tradeoffs: ['Release Interval 22% 변경', '우선순위 변경 후 30분간 dispatch 패턴 확인 필요'],
        operationItems: [
          'DISPATCH_RULE_OVERRIDE를 fab-wide로 적용하고 Release Interval을 22.0% 조정',
          'DE_FE_1 먼저 적용 후 Diffusion_FE_125에 동일 디스패치 룰 전파',
          '적용 직후 30분 동안 신규 Lot dispatch 패턴과 TG별 queue 적체 모니터링',
        ],
        metrics: [
          {
            label: '평균 대기',
            before: '62.96분',
            after: '58.0분',
            delta: '-4.96분',
            pctDelta: -7.9,
            tone: 'positive',
          },
          { label: 'WIP', before: '10 Lot', after: '8 Lot', delta: '-2 Lot', pctDelta: -20.0, tone: 'positive' },
          { label: 'Wait Ratio', before: '0.25', after: '0.18', delta: '-0.07', pctDelta: -28.0, tone: 'positive' },
          {
            label: '평균 가동률',
            before: '99.4%',
            after: '88.0%',
            delta: '-11.4%p',
            pctDelta: -11.5,
            tone: 'positive',
          },
          { label: '가용 Tool 비율', before: '100.0%', after: '100.0%', delta: '0.0%p', pctDelta: 0, tone: 'neutral' },
        ],
        impactTone: 'positive',
      },
      {
        planId: planConservativeId,
        actionLabel: 'conservative',
        actionKind: 'INTERVAL',
        title: 'conservative',
        summary: 'Release Interval을 15%만 조정합니다. 운영 리스크는 낮지만 복합 병목을 꺾기에는 개선 폭이 작습니다.',
        expectedImpact: '무대응 대비 q_time -5.26분, WIP -1.0, wait_ratio -0.08',
        riskText: '현재 기준으로는 DE_FE_1 대기와 WIP가 남아 재발 가능성이 큽니다.',
        confidence: 0.88,
        compositeScore: 0.083,
        scoreVerdict: 'modest_improvement',
        recommended: false,
        actionMetadata: { effort: 1, scope: 'fab-wide', reversibility: 'easy' },
        targetToolGroups: ['DE_FE_1', 'Diffusion_FE_125'],
        tradeoffs: ['부작용은 낮지만 회복 폭 제한', 'standard 대비 WIP 완화 부족'],
        operationItems: ['Release Interval을 15.0% 조정', '60분 후 DE_FE_1 q_time과 WIP 재확인'],
        metrics: [
          {
            label: '평균 대기',
            before: '62.96분',
            after: '82.0분',
            delta: '+19.04분',
            pctDelta: 30.2,
            tone: 'negative',
          },
          { label: 'WIP', before: '10 Lot', after: '11 Lot', delta: '+1 Lot', pctDelta: 10.0, tone: 'negative' },
          { label: 'Wait Ratio', before: '0.25', after: '0.42', delta: '+0.17', pctDelta: 68.0, tone: 'negative' },
          { label: '평균 가동률', before: '99.4%', after: '99.0%', delta: '-0.4%p', pctDelta: -0.4, tone: 'positive' },
          { label: '가용 Tool 비율', before: '100.0%', after: '100.0%', delta: '0.0%p', pctDelta: 0, tone: 'neutral' },
        ],
        impactTone: 'negative',
      },
      {
        planId: planAggressiveId,
        actionLabel: 'aggressive',
        actionKind: 'DISPATCH_RULE_OVERRIDE',
        title: 'aggressive',
        summary:
          'Release Interval 28% 조정과 Product_4 SuperHotLot 2건을 함께 적용합니다. DE_FE_1 개선은 크지만 Diffusion_FE_125 WIP 편중 위험이 있습니다.',
        expectedImpact: 'q_time -22.26분, WIP +2.0, wait_ratio -0.40, available_tool_ratio -0.14',
        riskText: 'Diffusion_FE_125 WIP가 18→20 Lot으로 악화되고 available_tool_ratio가 0.86까지 낮아질 수 있습니다.',
        confidence: 0.99,
        compositeScore: 0.576,
        scoreVerdict: 'high_effect_with_operational_risk',
        recommended: false,
        actionMetadata: { effort: 4, scope: 'fab-wide', reversibility: 'medium' },
        targetToolGroups: ['DE_FE_1', 'Diffusion_FE_125'],
        tradeoffs: ['Diffusion_FE_125 WIP 편중', '가용성 저하', 'SuperHotLot 적용 조건 확인 필요'],
        operationItems: [
          'Release Interval을 28.0% 조정',
          'Product_4 2건을 SuperHotLot(priority 30)로 상향',
          '15분 후 Diffusion_FE_125 WIP 편중 여부 확인',
        ],
        metrics: [
          {
            label: '평균 대기',
            before: '62.96분',
            after: '48.0분',
            delta: '-14.96분',
            pctDelta: -23.8,
            tone: 'positive',
          },
          { label: 'WIP', before: '10 Lot', after: '6 Lot', delta: '-4 Lot', pctDelta: -40.0, tone: 'positive' },
          { label: 'Wait Ratio', before: '0.25', after: '0.10', delta: '-0.15', pctDelta: -60.0, tone: 'positive' },
          {
            label: '평균 가동률',
            before: '99.4%',
            after: '80.0%',
            delta: '-19.4%p',
            pctDelta: -19.5,
            tone: 'positive',
          },
          {
            label: '가용 Tool 비율',
            before: '100.0%',
            after: '90.0%',
            delta: '-10.0%p',
            pctDelta: -10.0,
            tone: 'negative',
          },
        ],
        impactTone: 'positive',
      },
    ],
    recommendation: {
      actionLabel: 'standard',
      actionKind: 'DISPATCH_RULE_OVERRIDE',
      reason:
        'standard 안이 무대응 2시간 후 대비 q_time_min 16.260분, WIP 4.000 Lot, wait_ratio 0.320, utilization_avg 0.120을 개선하는 가장 큰 균형 효과를 보여 1위로 선택되었습니다.',
      structured: {
        headline: 'DISPATCH_RULE_OVERRIDE 추천 — CT/WIP 완화',
        primaryReason:
          '설비_포화(max_util 중심)와 utilization_avg 상승 추세(+0.138/h), WIP 증가 추세(+1.714/h)에 대응하는 조치입니다.',
        whyRecommended: {
          selectedBy: 'score',
          explanation:
            'standard 안은 DE_FE_1과 Diffusion_FE_125 모두에서 WIP·대기 완화 근거가 반복 확인됐고 aggressive의 가용성 저하를 피합니다.',
        },
        whyNotOthers: {
          conservative: '무대응 2시간 후 대비 완화폭이 작아 설비 포화와 WIP 증가를 충분히 꺾기 어렵습니다.',
          aggressive:
            'DE_FE_1 q_time은 더 줄지만 Diffusion_FE_125 available_tool_ratio가 0.86으로 낮아지고 WIP가 20 Lot까지 악화됩니다.',
        },
        caveats: [
          '시뮬레이션 기간은 120분 범위로, 그 이후의 연쇄 영향은 반영되지 않습니다.',
          '모든 KPI 수치는 시뮬레이션 예측값입니다.',
          '복합 TG 기준 비교는 무대응 2시간 후를 기준으로 해석해야 합니다.',
        ],
        confidenceLevel: 'high',
        immediateActions: [
          'DISPATCH_RULE_OVERRIDE를 fab-wide로 적용하고 Release Interval을 22.0% 조정',
          'DE_FE_1 먼저 적용 후 Diffusion_FE_125에 동일 디스패치 룰 전파',
          '적용 직후 30분 동안 신규 Lot dispatch 패턴과 TG별 queue 적체 모니터링',
        ],
        monitoringKpis: [
          'T+30분 q_time_min: DE_FE_1 58.0분, Diffusion_FE_125 30.0분 수준 유지',
          'T+30분 WIP: DE_FE_1 8 Lot, Diffusion_FE_125 8 Lot 수준 유지',
          'T+60분 wait_ratio: DE_FE_1 0.18, Diffusion_FE_125 0.65 수준으로 하향',
        ],
        rollbackCondition:
          '조치 30분 후 DE_FE_1 q_time_min이 96.39분에 근접해 재상승하거나 Diffusion_FE_125 WIP가 18 Lot 수준으로 되돌아가면 DISPATCH_RULE_OVERRIDE를 중단하고 Release Interval을 원복합니다.',
        recommendationStatus: 'AI 추천',
      },
    },
    decisionInfo: {
      decisionStatus: 'clear_winner',
      topLabel: 'standard',
      equivalentSet: [],
      tiebreakerUsed: null,
      decisionCaveat: 'standard 적용이 승인되었고 현장 적용 전 queue 적체 모니터링이 필요합니다.',
    },
    approvalInfo: {
      status: '승인',
      approvedBy: '은비',
      approvedRole: '팀원',
      approvedAt: '2026-06-14 23:12',
      comment: '즉시 적용 승인',
      rejectionReason: null,
    },
    hitlStatus: {
      hasDecision: true,
      latestDecision: 'APPROVED',
      selectedPlanId: planStandardId,
      comment: '즉시 적용 승인',
    },
    ragEvidence: {
      commonHits: RAG_SIMILAR_CASES,
      perPlan: {
        [planConservativeId]: {
          candidateSummary:
            'conservative는 동일 구성 사례에서 악화를 완화했지만 복합 병목 회복 폭이 제한적인 것으로 기록됐습니다.',
          riskLevel: 'low',
          evidenceStrength: 'moderate',
          effectOutlook: '부작용 낮음, 회복 폭 제한',
          claims: ['Release Interval +15%는 실행 리스크가 낮지만 DE_FE_1 q_time과 WIP를 충분히 낮추지 못함'],
        },
        [planStandardId]: {
          candidateSummary:
            'standard는 동일 구성 직접 사례에서 DE_FE_1과 Diffusion_FE_125의 WIP·대기를 함께 낮춘 반복 근거가 가장 안정적입니다.',
          riskLevel: 'low',
          evidenceStrength: 'strong',
          effectOutlook: '두 TG WIP·대기 균형 개선',
          claims: [
            'Release Interval +22%와 Product_3/Product_4 우선순위 상향으로 DE_FE_1 WIP 10→8',
            'Diffusion_FE_125 q_time 35.98→30분으로 완화',
          ],
        },
        [planAggressiveId]: {
          candidateSummary:
            'aggressive는 DE_FE_1 개선 폭이 가장 크지만 Diffusion_FE_125 WIP 편중과 가용성 저하가 반복 관측됐습니다.',
          riskLevel: 'medium',
          evidenceStrength: 'moderate',
          effectOutlook: '빠른 개선, 공정 간 편중 리스크',
          claims: ['Diffusion_FE_125 WIP가 20 Lot까지 증가하고 available_tool_ratio가 0.86으로 하락 가능'],
        },
      },
    },
  };
}

const candidateForecasts = {
  current: {
    DE_FE_1: {
      current: { q_time_min: 62.96, wip: 10, wait_ratio: 0.25, utilization_avg: 0.9943, available_tool_ratio: 1 },
      no_action: { q_time_min: 96.39, wip: 12, wait_ratio: 0.5, utilization_avg: 1, available_tool_ratio: 1 },
      action: { q_time_min: 96.39, wip: 12, wait_ratio: 0.5, utilization_avg: 1, available_tool_ratio: 1 },
    },
    Diffusion_FE_125: {
      current: { q_time_min: 35.98, wip: 5, wait_ratio: 0.25, utilization_avg: 0.8153, available_tool_ratio: 1 },
      no_action: { q_time_min: 46.26, wip: 18, wait_ratio: 3.5, utilization_avg: 1, available_tool_ratio: 1 },
      action: { q_time_min: 46.26, wip: 18, wait_ratio: 3.5, utilization_avg: 1, available_tool_ratio: 1 },
    },
  },
  conservative: {
    DE_FE_1: {
      current: { q_time_min: 62.96, wip: 10, wait_ratio: 0.25, utilization_avg: 0.9943, available_tool_ratio: 1 },
      no_action: { q_time_min: 96.39, wip: 12, wait_ratio: 0.5, utilization_avg: 1, available_tool_ratio: 1 },
      action: { q_time_min: 82, wip: 11, wait_ratio: 0.42, utilization_avg: 0.99, available_tool_ratio: 1 },
    },
    Diffusion_FE_125: {
      current: { q_time_min: 35.98, wip: 5, wait_ratio: 0.25, utilization_avg: 0.8153, available_tool_ratio: 1 },
      no_action: { q_time_min: 46.26, wip: 18, wait_ratio: 3.5, utilization_avg: 1, available_tool_ratio: 1 },
      action: { q_time_min: 41, wip: 14, wait_ratio: 2.6, utilization_avg: 0.96, available_tool_ratio: 1 },
    },
  },
  standard: {
    DE_FE_1: {
      current: { q_time_min: 62.96, wip: 10, wait_ratio: 0.25, utilization_avg: 0.9943, available_tool_ratio: 1 },
      no_action: { q_time_min: 96.39, wip: 12, wait_ratio: 0.5, utilization_avg: 1, available_tool_ratio: 1 },
      action: { q_time_min: 58, wip: 8, wait_ratio: 0.18, utilization_avg: 0.88, available_tool_ratio: 1 },
    },
    Diffusion_FE_125: {
      current: { q_time_min: 35.98, wip: 5, wait_ratio: 0.25, utilization_avg: 0.8153, available_tool_ratio: 1 },
      no_action: { q_time_min: 46.26, wip: 18, wait_ratio: 3.5, utilization_avg: 1, available_tool_ratio: 1 },
      action: { q_time_min: 30, wip: 8, wait_ratio: 0.65, utilization_avg: 0.82, available_tool_ratio: 1 },
    },
  },
  aggressive: {
    DE_FE_1: {
      current: { q_time_min: 62.96, wip: 10, wait_ratio: 0.25, utilization_avg: 0.9943, available_tool_ratio: 1 },
      no_action: { q_time_min: 96.39, wip: 12, wait_ratio: 0.5, utilization_avg: 1, available_tool_ratio: 1 },
      action: { q_time_min: 48, wip: 6, wait_ratio: 0.1, utilization_avg: 0.8, available_tool_ratio: 0.9 },
    },
    Diffusion_FE_125: {
      current: { q_time_min: 35.98, wip: 5, wait_ratio: 0.25, utilization_avg: 0.8153, available_tool_ratio: 1 },
      no_action: { q_time_min: 46.26, wip: 18, wait_ratio: 3.5, utilization_avg: 1, available_tool_ratio: 1 },
      action: { q_time_min: 24, wip: 20, wait_ratio: 0.45, utilization_avg: 0.74, available_tool_ratio: 0.86 },
    },
  },
} satisfies Record<string, ReportV1['actions']['candidates'][number]['per_tg_forecasts']>;

export const DE_FE_1_REPORT_V1: ReportV1 = {
  schema_version: 'report/1.0',
  meta: {
    toolgroup: 'DE_FE_1',
    process_name: 'DE_FE_1',
    severity: 'Critical',
    severity_token: 'danger',
    severity_priority: 0,
    detected_at: '2026-06-14 23:12',
    generated_at: '2026-06-14 23:12:46',
    snapshot_time: 3780,
    horizon_min: 120,
    schema_version: 'report/1.0',
  },
  approval: {
    status: '승인',
    status_token: 'approved',
    approver_name: '은비',
    approver_role: '팀원',
    approved_at: '2026-06-14 23:12',
    comment: '즉시 적용 승인',
    rejection_reason: null,
    selected_label: 'standard',
  },
  risk: {
    score: 80.3,
    score_unit: 'score',
    score_threshold_state: 'danger',
    composite_score: 0.8031,
    probability: 0.9958,
  },
  confidence: {
    level: 'HIGH',
    level_token: 'high',
    needs_more_data: false,
    g_star_probability: 0.6867,
  },
  if_no_action: {
    available: true,
    will_get_worse: true,
    horizon_min: 120,
    kpi_changes: [
      {
        kpi: 'q_time_min',
        unit: 'min',
        now: 62.96,
        after: 96.39,
        delta: 33.43,
        pct_change: 53.1,
        reliability_token: 'HIGH',
      },
      { kpi: 'wip', unit: 'lots', now: 10, after: 12, delta: 2, pct_change: 20, reliability_token: 'HIGH' },
      {
        kpi: 'wait_ratio',
        unit: 'ratio',
        now: 0.25,
        after: 0.5,
        delta: 0.25,
        pct_change: 100,
        reliability_token: 'HIGH',
      },
      {
        kpi: 'utilization_avg',
        unit: 'ratio',
        now: 0.994,
        after: 1,
        delta: 0.006,
        pct_change: 0.6,
        reliability_token: 'MED',
      },
    ],
  },
  bottleneck_kpis: [
    {
      key: 'risk_score',
      label: 'Risk Score',
      value: 80.3,
      unit: 'score',
      threshold_state: 'danger',
      prev_value: null,
      delta: null,
      pct_change: null,
    },
    {
      key: 'q_time_min',
      label: '평균 대기시간',
      value: 62.96,
      unit: 'min',
      threshold_state: null,
      prev_value: 76.22,
      delta: -13.26,
      pct_change: -17.4,
    },
    {
      key: 'wip',
      label: 'WIP',
      value: 10,
      unit: 'lots',
      threshold_state: null,
      prev_value: 13,
      delta: -3,
      pct_change: -23.08,
    },
    {
      key: 'wait_ratio',
      label: 'Wait Ratio',
      value: 0.25,
      unit: 'ratio',
      threshold_state: 'ok',
      prev_value: 0.63,
      delta: -0.38,
      pct_change: -60.32,
    },
    {
      key: 'utilization_avg',
      label: '평균 가동률',
      value: 0.9943,
      unit: 'ratio',
      threshold_state: 'danger',
      prev_value: 0.9761,
      delta: 0.0182,
      pct_change: 1.86,
    },
    {
      key: 'available_tool_ratio',
      label: '가용 호기 비율',
      value: 1,
      unit: 'ratio',
      threshold_state: null,
      prev_value: 1,
      delta: 0,
      pct_change: 0,
    },
    {
      key: 'max_util',
      label: '최대 가동률',
      value: 1,
      unit: 'ratio',
      threshold_state: 'danger',
      prev_value: 1,
      delta: 0,
      pct_change: 0,
    },
  ],
  data_quality: { status: 'ok', warnings: [] },
  cause: {
    summary: DE_FE_1_CAUSE.judgment?.causeSummary ?? '',
    primary: {
      category: '설비_포화',
      feature: 'max_util',
      confidence: 'HIGH',
      confidence_token: 'high',
      reasoning: DE_FE_1_CAUSE.judgment?.primaryReasoning ?? '',
    },
    secondary_categories: ['WIP_누적'],
    categories: DE_FE_1_CAUSE.causeCategories!.map((category) => ({
      name: category.name,
      features: category.features,
      shap_share_pct: category.shapSharePct,
      n_trend_significant: category.nTrendSignificant,
      upstream_match: category.upstreamMatch,
      g_star_confirmed: category.gStarConfirmed,
      total_score: category.totalScore,
      confidence: category.confidence,
      confidence_token: category.confidence.toLowerCase(),
    })),
    shap_top: DE_FE_1_CAUSE.shapFeatures.map((feature) => ({
      rank: feature.rank,
      feature: feature.feature,
      value: feature.kpiValue ?? 0,
      shap: feature.shapValue ?? 0,
      contribution_pct: feature.contributionPct ?? feature.importance * 100,
      direction_token: 'bottleneck_positive',
    })),
    trend_series: {
      time_labels: ['T-300분', 'T-240분', 'T-180분', 'T-120분', 'T-60분', 'T-0분'],
      time_offsets_min: [-300, -240, -180, -120, -60, 0],
      features: {
        q_time_min: {
          values: [0, 0, 22.24, 63.77, 76.22, 62.96],
          slope_per_hour: 16.714,
          r2: 0.831,
          significant: true,
        },
        wip: { values: [4, 4, 10, 13, 13, 10], slope_per_hour: 1.7143, r2: 0.6122, significant: true },
        utilization_avg: {
          values: [0.3389, 0.5, 0.8875, 1, 0.9761, 0.9943],
          slope_per_hour: 0.1377,
          r2: 0.7947,
          significant: true,
        },
      },
    },
    upstream_suspects: ['DE_FE_86'],
    consensus_axes: {
      shap_supports: true,
      trend_supports: true,
      upstream_supports: true,
      g_star_supports: false,
      axes_agreed_count: 3,
    },
    g_star: {
      confirmed: false,
      probability: 0.6867,
      monte_carlo: { n_total: 106, n_alarm: 4, alarm_ratio_pct: 3.8 },
      upstream_confirmed_toolgroups: ['DE_FE_86'],
      significant_kpis: [],
    },
  },
  diffusion: {
    bottleneck_location: 'DE_FE_1',
    diffusion_path: ['DE_FE_1', 'Diffusion_FE_125'],
    high_impact_processes: [
      {
        toolgroup: 'Diffusion_FE_125',
        utilization_pct: 81.5,
        wait_ratio: 0.25,
        wip: 5,
        impact_score: 0.6867,
        data_quality_flags: [],
      },
    ],
    low_impact_processes: [],
    forward_simulation: {
      available: true,
      horizon_min: 120,
      results: [
        {
          toolgroup: 'DE_FE_1',
          q_time_min_future: 96.39,
          wait_ratio_future: 0.5,
          wip_future: 12,
          is_bottleneck_predicted: true,
        },
      ],
    },
    line_stop_expected_min: 1670,
    risk_level: 'Critical',
    risk_level_token: 'danger',
  },
  actions: {
    available: true,
    candidates: [
      {
        label: '현재상태',
        kind: 'NO_ACTION',
        is_baseline: true,
        is_approved: false,
        description: '조치 없음 — 병목 유지',
        target_toolgroups: [],
        params: null,
        kpi_impact: [
          {
            kpi: 'q_time_min',
            unit: 'min',
            now: 62.96,
            after: 96.39,
            delta: 33.43,
            pct_change: 53.1,
            verdict: 'worsening',
            verdict_token: 'worsening',
            confidence: 1,
            ci_low: 0,
            ci_high: 0,
            ci_width: 0,
            paired_t_p: null,
            significant: null,
          },
          {
            kpi: 'wip',
            unit: 'lots',
            now: 10,
            after: 12,
            delta: 2,
            pct_change: 20,
            verdict: 'worsening',
            verdict_token: 'worsening',
            confidence: 1,
            ci_low: 0,
            ci_high: 0,
            ci_width: 0,
            paired_t_p: null,
            significant: null,
          },
          {
            kpi: 'wait_ratio',
            unit: 'ratio',
            now: 0.25,
            after: 0.5,
            delta: 0.25,
            pct_change: 100,
            verdict: 'worsening',
            verdict_token: 'worsening',
            confidence: 1,
            ci_low: 0,
            ci_high: 0,
            ci_width: 0,
            paired_t_p: null,
            significant: null,
          },
          {
            kpi: 'utilization_avg',
            unit: 'ratio',
            now: 0.9943,
            after: 1,
            delta: 0.0057,
            pct_change: 0.6,
            verdict: 'worsening',
            verdict_token: 'worsening',
            confidence: 1,
            ci_low: 0,
            ci_high: 0,
            ci_width: 0,
            paired_t_p: null,
            significant: null,
          },
          {
            kpi: 'available_tool_ratio',
            unit: 'ratio',
            now: 1,
            after: 1,
            delta: 0,
            pct_change: 0,
            verdict: 'no_change',
            verdict_token: 'no_change',
            confidence: 1,
            ci_low: 0,
            ci_high: 0,
            ci_width: 0,
            paired_t_p: null,
            significant: null,
          },
        ],
        operational: { effort: 0, effort_max: 5, scope: 'none', reversibility: 'high' },
        simulation: { paired_n: 0, confidence: null, verdict: 'no_action' },
        composite_score: 0,
        tradeoffs: [],
        comparison_basis: '현재 기준',
        per_tg_forecasts: candidateForecasts.current,
      },
      {
        label: 'conservative',
        kind: 'INTERVAL',
        is_baseline: false,
        is_approved: false,
        description: 'Release Interval Δ15.0%',
        target_toolgroups: ['DE_FE_1', 'Diffusion_FE_125'],
        params: { release_interval_delta_pct: 15 },
        kpi_impact: [
          {
            kpi: 'q_time_min',
            unit: 'min',
            now: 96.39,
            after: 82,
            delta: -5.26,
            pct_change: -5.5,
            verdict: 'no_significant_change',
            verdict_token: 'modest',
            confidence: 0.88,
            ci_low: -10,
            ci_high: 2,
            ci_width: 12,
            paired_t_p: 0.12,
            significant: false,
          },
          {
            kpi: 'wip',
            unit: 'lots',
            now: 12,
            after: 11,
            delta: -1,
            pct_change: -8.3,
            verdict: 'no_significant_change',
            verdict_token: 'modest',
            confidence: 0.88,
            ci_low: -2,
            ci_high: 0,
            ci_width: 2,
            paired_t_p: 0.18,
            significant: false,
          },
          {
            kpi: 'wait_ratio',
            unit: 'ratio',
            now: 0.5,
            after: 0.42,
            delta: -0.08,
            pct_change: -16,
            verdict: 'no_significant_change',
            verdict_token: 'modest',
            confidence: 0.88,
            ci_low: -0.12,
            ci_high: 0.02,
            ci_width: 0.14,
            paired_t_p: 0.22,
            significant: false,
          },
          {
            kpi: 'utilization_avg',
            unit: 'ratio',
            now: 1,
            after: 0.99,
            delta: -0.01,
            pct_change: -1,
            verdict: 'no_significant_change',
            verdict_token: 'modest',
            confidence: 0.88,
            ci_low: -0.03,
            ci_high: 0.01,
            ci_width: 0.04,
            paired_t_p: 0.28,
            significant: false,
          },
          {
            kpi: 'available_tool_ratio',
            unit: 'ratio',
            now: 1,
            after: 1,
            delta: 0,
            pct_change: 0,
            verdict: 'no_change',
            verdict_token: 'no_change',
            confidence: 0.88,
            ci_low: 0,
            ci_high: 0,
            ci_width: 0,
            paired_t_p: 0.8,
            significant: false,
          },
        ],
        operational: { effort: 1, effort_max: 5, scope: 'fab-wide', reversibility: 'easy' },
        simulation: { paired_n: 10, confidence: 0.88, verdict: 'no_significant_change' },
        composite_score: 0.083,
        tradeoffs: ['회복 폭 제한', '복합 병목 재발 가능성'],
        comparison_basis: '무대응 120분 후 기준',
        per_tg_forecasts: candidateForecasts.conservative,
      },
      {
        label: 'standard',
        kind: 'DISPATCH_RULE_OVERRIDE',
        is_baseline: false,
        is_approved: true,
        description: 'Release Interval Δ22.0%',
        target_toolgroups: ['DE_FE_1', 'Diffusion_FE_125'],
        params: { release_interval_delta_pct: 22, priority_products: ['Product_3', 'Product_4'] },
        kpi_impact: [
          {
            kpi: 'q_time_min',
            unit: 'min',
            now: 96.39,
            after: 58,
            delta: -16.26,
            pct_change: -16.9,
            verdict: 'improved',
            verdict_token: 'improved',
            confidence: 0.99,
            ci_low: -20,
            ci_high: -12,
            ci_width: 8,
            paired_t_p: 0.006,
            significant: true,
          },
          {
            kpi: 'wip',
            unit: 'lots',
            now: 12,
            after: 8,
            delta: -4,
            pct_change: -33.3,
            verdict: 'improved',
            verdict_token: 'improved',
            confidence: 0.99,
            ci_low: -5,
            ci_high: -3,
            ci_width: 2,
            paired_t_p: 0.008,
            significant: true,
          },
          {
            kpi: 'wait_ratio',
            unit: 'ratio',
            now: 0.5,
            after: 0.18,
            delta: -0.32,
            pct_change: -64,
            verdict: 'improved',
            verdict_token: 'improved',
            confidence: 0.99,
            ci_low: -0.38,
            ci_high: -0.2,
            ci_width: 0.18,
            paired_t_p: 0.012,
            significant: true,
          },
          {
            kpi: 'utilization_avg',
            unit: 'ratio',
            now: 1,
            after: 0.88,
            delta: -0.12,
            pct_change: -12,
            verdict: 'improved',
            verdict_token: 'improved',
            confidence: 0.99,
            ci_low: -0.16,
            ci_high: -0.08,
            ci_width: 0.08,
            paired_t_p: 0.018,
            significant: true,
          },
          {
            kpi: 'available_tool_ratio',
            unit: 'ratio',
            now: 1,
            after: 1,
            delta: 0,
            pct_change: 0,
            verdict: 'no_change',
            verdict_token: 'no_change',
            confidence: 0.99,
            ci_low: 0,
            ci_high: 0,
            ci_width: 0,
            paired_t_p: 0.75,
            significant: false,
          },
        ],
        operational: { effort: 2, effort_max: 5, scope: 'fab-wide', reversibility: 'easy' },
        simulation: { paired_n: 10, confidence: 0.99, verdict: 'improved' },
        composite_score: 0.651,
        tradeoffs: ['Release Interval 22% 변경', '30분 dispatch 패턴 모니터링 필요'],
        comparison_basis: '무대응 120분 후 기준',
        per_tg_forecasts: candidateForecasts.standard,
      },
      {
        label: 'aggressive',
        kind: 'DISPATCH_RULE_OVERRIDE',
        is_baseline: false,
        is_approved: false,
        description: 'Release Interval Δ28.0% + Product_4 SuperHotLot',
        target_toolgroups: ['DE_FE_1', 'Diffusion_FE_125'],
        params: { release_interval_delta_pct: 28, super_hot_lot_products: ['Product_4'] },
        kpi_impact: [
          {
            kpi: 'q_time_min',
            unit: 'min',
            now: 96.39,
            after: 48,
            delta: -22.26,
            pct_change: -23.1,
            verdict: 'improved',
            verdict_token: 'improved',
            confidence: 0.99,
            ci_low: -30,
            ci_high: -16,
            ci_width: 14,
            paired_t_p: 0.004,
            significant: true,
          },
          {
            kpi: 'wip',
            unit: 'lots',
            now: 12,
            after: 6,
            delta: 2,
            pct_change: 16.7,
            verdict: 'degraded',
            verdict_token: 'degraded',
            confidence: 0.99,
            ci_low: 1,
            ci_high: 4,
            ci_width: 3,
            paired_t_p: 0.018,
            significant: true,
          },
          {
            kpi: 'wait_ratio',
            unit: 'ratio',
            now: 0.5,
            after: 0.1,
            delta: -0.4,
            pct_change: -80,
            verdict: 'improved',
            verdict_token: 'improved',
            confidence: 0.99,
            ci_low: -0.5,
            ci_high: -0.3,
            ci_width: 0.2,
            paired_t_p: 0.006,
            significant: true,
          },
          {
            kpi: 'utilization_avg',
            unit: 'ratio',
            now: 1,
            after: 0.8,
            delta: -0.2,
            pct_change: -20,
            verdict: 'improved',
            verdict_token: 'improved',
            confidence: 0.99,
            ci_low: -0.25,
            ci_high: -0.14,
            ci_width: 0.11,
            paired_t_p: 0.01,
            significant: true,
          },
          {
            kpi: 'available_tool_ratio',
            unit: 'ratio',
            now: 1,
            after: 0.9,
            delta: -0.14,
            pct_change: -14,
            verdict: 'degraded',
            verdict_token: 'degraded',
            confidence: 0.99,
            ci_low: -0.2,
            ci_high: -0.08,
            ci_width: 0.12,
            paired_t_p: 0.009,
            significant: true,
          },
        ],
        operational: { effort: 4, effort_max: 5, scope: 'fab-wide', reversibility: 'medium' },
        simulation: { paired_n: 10, confidence: 0.99, verdict: 'mixed' },
        composite_score: 0.576,
        tradeoffs: ['Diffusion_FE_125 WIP 편중', '가용성 저하', 'SuperHotLot 조건 확인 필요'],
        comparison_basis: '무대응 120분 후 기준',
        per_tg_forecasts: candidateForecasts.aggressive,
      },
    ],
    approved_label: 'standard',
    decision_status: '명확한 1위',
    decision_status_token: 'approved',
    equivalent_set: [],
    tiebreaker_used: null,
    decision_caveat:
      'standard 적용이 승인되었습니다. 적용 직후 30분 동안 신규 Lot dispatch 패턴과 queue 적체를 확인하세요.',
    recommendation: {
      headline: 'DISPATCH_RULE_OVERRIDE 추천 — CT/WIP 완화',
      primary_reason:
        '설비_포화(max_util 중심)와 utilization_avg 상승 추세(+0.138/h), WIP 증가 추세(+1.714/h)에 대응하는 조치입니다. 기준은 무대응 2시간 후이며, 적용 시 q_time_min은 96.39분/46.26분 대비 58.0분/30.0분으로, WIP는 12.0개/18.0개 대비 8.0개/8.0개로 완화되는 시뮬레이션 예측값입니다.',
      confidence_level: 'high',
      confidence_token: 'high',
      tradeoffs: [
        'Diffusion_FE_125의 available_tool_ratio는 무대응 2시간 후 1.0에서 1.0으로 유지되지만, aggressive 안에서는 0.86으로 낮아집니다.',
      ],
      why_not_others: [
        {
          label: 'conservative',
          reason:
            '무대응 2시간 후 대비 q_time_min 5.260, WIP 1.000, wait_ratio 0.080 완화로는 설비 포화와 WIP 증가를 충분히 꺾기 어렵습니다.',
        },
        {
          label: 'aggressive',
          reason:
            'q_time_min은 더 크게 줄지만 Diffusion_FE_125의 available_tool_ratio가 0.86으로 떨어지고 WIP가 20 Lot까지 악화되어 운영 리스크가 큽니다.',
        },
      ],
      caveats: [
        '시뮬레이션 기간은 120분 범위로, 그 이후의 연쇄 영향은 반영되지 않습니다.',
        '모든 KPI 수치는 시뮬레이션 예측값입니다.',
        '복합 TG 기준 비교는 무대응 2시간 후를 기준으로 해석해야 합니다.',
      ],
      tiebreaker_chain: [],
      selected_by: 'score',
    },
    playbook: {
      available: true,
      immediate_actions: [
        { order: 1, text: 'DISPATCH_RULE_OVERRIDE를 fab-wide로 적용하고 Release Interval을 22.0% 조정합니다.' },
        { order: 2, text: '적용 순서는 DE_FE_1 먼저, 이어서 Diffusion_FE_125에 동일한 디스패치 룰을 전파합니다.' },
        { order: 3, text: '적용 직후 30분 동안 신규 lot dispatch 패턴과 TG별 queue 적체를 모니터링합니다.' },
      ],
      monitoring: [
        {
          kpi: 'q_time_min',
          target: 'DE_FE_1 58.0분, Diffusion_FE_125 30.0분 수준 유지',
          unit: '',
          check_after_min: 30,
        },
        { kpi: 'wip', target: 'DE_FE_1 8개, Diffusion_FE_125 8개 수준 유지', unit: '', check_after_min: 30 },
        {
          kpi: 'wait_ratio',
          target: 'DE_FE_1 0.18, Diffusion_FE_125 0.65 수준으로 하향',
          unit: '',
          check_after_min: 60,
        },
      ],
      rollback_condition:
        '조치 30분 후 DE_FE_1 q_time_min이 96.39분에 근접해 재상승하거나 Diffusion_FE_125 WIP가 18 Lot 수준으로 되돌아가면 DISPATCH_RULE_OVERRIDE를 중단하고 Release Interval을 원복합니다.',
    },
  },
  sections: {
    summary:
      'DE_FE_1에서 설비 포화가 핵심 원인으로 확인되며 병목 수준은 Critical입니다. standard 적용이 승인되었고 WIP·Q-time·wait_ratio·utilization_avg가 모두 개선됩니다.',
    cause:
      '주원인은 설비_포화이며 utilization_avg가 한계권에 머무르고 WIP가 누적되어 투입을 제때 소화하지 못하는 상태입니다.',
    action: 'standard: DISPATCH_RULE_OVERRIDE / Release Interval Δ22.0% → DE_FE_1 WIP 10→8, q_time 62.96→58.0분.',
  },
  rendered: {
    markdown: '# DE_FE_1 병목 대응 보고서\n\n병목 위험 점수 80.3. standard DISPATCH_RULE_OVERRIDE 승인.',
  },
  rag_evidence: {
    common_hits: RAG_SIMILAR_CASES.map((item) => ({
      case_id: item.caseId,
      score: item.score,
      tg_code: item.tgCode,
      cause_summary: item.summary,
      report_title: item.reportTitle,
    })),
    candidates: [
      {
        label: 'conservative',
        evidence: {
          candidate_summary: 'conservative는 부작용은 낮지만 회복 폭이 제한적입니다.',
          risk_level: 'low',
          evidence_strength: 'moderate',
          effect_outlook: '완화 폭 제한',
          claims: ['Release Interval +15%는 복합 병목 회복 속도가 제한적입니다.'],
        },
      },
      {
        label: 'standard',
        evidence: {
          candidate_summary: 'standard는 두 TG의 WIP와 대기를 함께 낮춘 반복 근거가 가장 안정적입니다.',
          risk_level: 'low',
          evidence_strength: 'strong',
          effect_outlook: '균형 개선',
          claims: ['Release Interval +22%와 제한적 우선순위 조합이 WIP와 대기를 균형 있게 낮췄습니다.'],
        },
      },
      {
        label: 'aggressive',
        evidence: {
          candidate_summary: '대기 개선은 가장 빠르지만 Diffusion_FE_125 WIP 편중과 가용성 저하가 동반됩니다.',
          risk_level: 'medium',
          evidence_strength: 'moderate',
          effect_outlook: '빠른 개선, 운영 리스크 동반',
          claims: ['SuperHotLot 포함 시 Diffusion_FE_125 WIP 편중이 반복 관측됐습니다.'],
        },
      },
    ],
    comparison: {
      ranking_status: 'clear_winner',
      ranking: [],
      rag_summary:
        'standard은 동일 구성 직접 사례에서 DE_FE_1과 Diffusion_FE_125의 WIP·대기를 함께 낮춘 반복 근거가 가장 안정적입니다.',
      overall_comment:
        'aggressive는 더 빠른 개선 사례가 있으나 Diffusion_FE_125 WIP 편중과 가용성 저하가 함께 관측되어 standard가 운영 리스크 대비 적합합니다.',
    },
  },
};

export const MOCK_BNC_CAUSE_ANALYSIS: Record<string, BncCauseAnalysis> = {
  [DE_FE_1_CASE_ID]: DE_FE_1_CAUSE,
};

export const MOCK_BNC_ACTION_PLANS: Record<string, BncActionPlansPayload> = {
  [DE_FE_1_CASE_ID]: buildActionPlans(DE_FE_1_CASE_ID),
};

export const MOCK_BNC_REPORTS: Record<string, BncReportPayload> = {
  [DE_FE_1_CASE_ID]: {
    reportId: `report-${DE_FE_1_CASE_ID}`,
    caseId: DE_FE_1_CASE_ID,
    summary:
      'DE_FE_1에서 Critical 병목이 감지되었고(probability 99.6%, risk score 80.3), 주요 원인은 설비_포화(max_util)입니다. standard DISPATCH_RULE_OVERRIDE 적용이 승인되었습니다.',
    rootCauseText:
      '주요 원인은 설비_포화(max_util, max_util_delta_120, utilization_avg)이며 WIP_누적이 보조 원인입니다. 대기_누적·공급_부족은 근거가 약해 기각되었습니다.',
    actionComparisonText:
      'standard DISPATCH_RULE_OVERRIDE 권장 및 승인. Release Interval Δ22.0% 적용 시 DE_FE_1 q_time 62.96→58.0분, WIP 10→8 Lot, wait_ratio 0.25→0.18로 개선됩니다.',
    timeline: [
      { time: DETECTED_AT, event: 'DE_FE_1 병목 감지 (Critical, risk score 80.3, probability 99.6%)' },
      { time: '2026-06-14T14:12:10Z', event: '원인 분석 완료 — 설비_포화 주원인, DE_FE_86 업스트림 부담 확인' },
      { time: '2026-06-14T14:12:42Z', event: '대응안 비교 완료 — standard DISPATCH_RULE_OVERRIDE 명확한 1위' },
      { time: GENERATED_AT, event: '은비(팀원) standard 안 즉시 적용 승인 및 최종 리포트 생성' },
    ],
    hasPdf: false,
    generatedAt: GENERATED_AT,
    regeneratedCount: 0,
    qdrantIndexed: true,
    reportV1: DE_FE_1_REPORT_V1,
  },
};
