import { MOCK_FINAL_BOTTLENECK_REPORT } from '@/constants/mockData/finalBottleneckReport';

import type { ActionHistoryDetail, ActionHistoryItem } from '@/types/report';

export const MOCK_ACTION_HISTORY_ITEMS: ActionHistoryItem[] = [
  {
    caseId: 'hist-defmet-fe-43-20260609',
    displayDay: '2026-06-09',
    targetTgText: 'DefMet_FE_43 외 13개',
    tgName: 'DefMet_FE_43',
    areaName: 'Defect Metrology',
    detectedAt: '2026-06-09T08:21:00Z',
    riskGrade: 'CRITICAL',
    selectedPlanTitle: 'DISPATCH_RULE_OVERRIDE',
    planType: '스케줄링',
    decidedBy: { userId: 'system-auto', userName: 'AUTO' },
    decision: 'APPROVED',
    decidedAt: '2026-06-09T08:22:10Z',
    estAvgWaitDelta: 0,
    estDeliveryComplianceDelta: 0,
    status: 'RESOLVED',
    hasReport: true,
    reportTypes: ['ACTION'],
  },
  {
    caseId: 'hist-litho-be-110-20260521',
    displayDay: 'Day 22',
    targetTgText: 'DE_FE_72',
    tgName: 'Litho_BE_110',
    areaName: 'Lithography',
    detectedAt: '2026-05-21T23:35:00Z',
    riskGrade: 'CRITICAL',
    selectedPlanTitle: '대기 Lot 우선순위 부스트',
    planType: '스케줄링',
    decidedBy: { userId: 'user-park', userName: '김엔지니어' },
    decision: 'APPROVED',
    decidedAt: '2026-05-21T23:48:00Z',
    estAvgWaitDelta: -0.082,
    estDeliveryComplianceDelta: 0.4,
    status: 'RESOLVED',
    hasReport: true,
    reportTypes: ['ACTION'],
  },
  {
    caseId: 'hist-cmp-be-12-20260520',
    displayDay: 'Day 18',
    targetTgText: 'Litho_BE_110',
    tgName: 'CMP_BE_12',
    areaName: 'CMP',
    detectedAt: '2026-05-20T08:10:00Z',
    riskGrade: 'HIGH',
    selectedPlanTitle: 'CR Dispatcher 적용',
    planType: '스케줄링',
    decidedBy: { userId: 'user-lee', userName: '이오퍼레이터' },
    decision: 'APPROVED',
    decidedAt: '2026-05-20T08:22:00Z',
    estAvgWaitDelta: 1.639,
    estDeliveryComplianceDelta: 3,
    status: 'RESOLVED',
    hasReport: true,
    reportTypes: ['ACTION'],
  },
  {
    caseId: 'hist-photo-fe-28-20260519',
    displayDay: 'Day 15',
    targetTgText: 'DE_BE_67',
    tgName: 'Photo_FE_28',
    areaName: 'Photo',
    detectedAt: '2026-05-19T15:05:00Z',
    riskGrade: 'HIGH',
    selectedPlanTitle: 'Batch 최솟값 완화',
    planType: '스케줄링',
    decidedBy: { userId: 'user-choi', userName: '최엔지니어' },
    decision: 'APPROVED',
    decidedAt: '2026-05-19T15:18:00Z',
    estAvgWaitDelta: -0.044,
    estDeliveryComplianceDelta: 0.5,
    status: 'RESOLVED',
    hasReport: false,
    reportTypes: [],
  },
];

export const MOCK_ACTION_HISTORY_DETAILS: Record<string, ActionHistoryDetail> = Object.fromEntries(
  MOCK_ACTION_HISTORY_ITEMS.map((item, index) => [
    item.caseId,
    {
      caseId: item.caseId,
      displayDay: item.displayDay,
      targetTgText: item.targetTgText,
      tgName: item.tgName,
      areaName: item.areaName,
      riskGrade: item.riskGrade,
      bottleneckProb: [0.999, 0.974, 0.891, 0.842][index],
      detectedAt: item.detectedAt,
      resolvedAt: '2026-05-22T02:00:00Z',
      hitlDecision: {
        decisionId: `decision-${item.caseId}`,
        decision: item.decision,
        selectedPlanTitle: item.selectedPlanTitle,
        comment: item.decision === 'APPROVED' ? '선택 대응안 승인' : '효과 대비 운영 리스크가 높아 반려',
        decidedBy: item.decidedBy,
        decidedAt: item.decidedAt,
      },
      baseline: {
        throughput: 3468 - index * 74,
        avgWaitDay: 10.551 + index * 0.31,
        deliveryCompliance: 95 - index * 0.6,
      },
      actionPlans: [
        {
          planSeq: 0,
          planTitle: '베이스라인',
          planType: '-',
          estThroughputDelta: 0,
          estAvgWaitDelta: 0,
          estDeliveryComplianceDelta: 0,
          estDelayDelta: 0,
          isSelected: false,
        },
        {
          planSeq: 1,
          planTitle: item.selectedPlanTitle,
          planType: item.planType,
          estThroughputDelta: 22 - index * 2,
          estAvgWaitDelta: item.estAvgWaitDelta,
          estDeliveryComplianceDelta: item.estDeliveryComplianceDelta,
          estDelayDelta: -0.05,
          isSelected: true,
        },
        {
          planSeq: 2,
          planTitle: 'LOT_RELEASE_THROTTLE',
          planType: '생산계획',
          estThroughputDelta: -4,
          estAvgWaitDelta: -0.04,
          estDeliveryComplianceDelta: 0.2,
          estDelayDelta: -0.01,
          isSelected: false,
        },
      ],
      reportId: `report-${item.caseId}`,
      hasPdf: item.hasReport,
      finalReport: MOCK_FINAL_BOTTLENECK_REPORT,
    },
  ])
);
